### ISSUE TITLE
Don't see Notes on the Account Page (8.1.1)

### ISSUE THREAD

**Issue by parijke** [salesagility/SuiteCRM-Core#104]
When I add a note to an account, I don't see any possibility to view it when I am on the Account page. What am I missing here?

![image](https://user-images.githubusercontent.com/7671998/170820302-d3ed8727-8a5e-4fe9-a0da-5b55a345c49c.png)
![image](https://user-images.githubusercontent.com/7671998/170820321-ee49487a-23e0-4e00-8bed-10bca3fc5040.png)

**Comment by sebastianbrosch** [comment]
You can see the notes by enabling the "History" subpanel. There you also have the possibility to add new notes for the currently opened Account. You can also create a new subpanel. You can start here: https://community.suitecrm.com/t/how-can-we-add-notes-as-a-subpanel-in-accounts-module/71133

**Comment by parijke** [comment]
Thanks worked!
