### ISSUE TITLE
Error when adding Fields to Product

### ISSUE THREAD

**Issue by romleinster** [salesagility/SuiteCRM-Core#11]
#### Issue
Went to Admin > Studio to add field to Products and got an error.

#### Expected Behavior
I should be able to add fields to modules.

#### Actual Behavior
Interface briefly flashes "Failed to Retrieve Data"
This error is in php logs:

```
PHP Fatal error:  Uncaught Error: Attempt to modify property "vardefs" on null in 
/srv/http/suitecrm8/public/legacy/modules/ModuleBuilder/views/view.modulefields.php:109

Stack trace:
#0 /srv/http/suitecrm8/public/legacy/include/MVC/View/SugarView.php(210): 
ViewModulefields->display()

#1 /srv/http/suitecrm8/public/legacy/include/MVC/Controller/SugarController.php(432): SugarView->process()

#2 /srv/http/suitecrm8/public/legacy/include/MVC/Controller/SugarController.php(363): SugarController->processView()

#3 /srv/http/suitecrm8/public/legacy/include/MVC/SugarApplication.php(101): SugarController->execute()

#4 /srv/http/suitecrm8/public/legacy/index.php(52): SugarApplication->execute

#5 {main}
  thrown in /srv/http/suitecrm8/public/legacy/modules/ModuleBuilder/views/view.modulefields.php on line 109, referer: http://myserver/suitecrm8/legacy/index.php?type=studio&module=ModuleBuilder&action=index
```
#### Steps to Reproduce
Not sure if the data imports I had done earlier (CSV files exported from an earlier version of SuiteCRM) caused this or if it's some factor of my install environment, but presumably just install suitecrm 8.0.0-beta2 and try to add fields to a module. I imported data into products, invoices, and a few other tables.

#### Your Environment

* SuiteCRM 8.0.0-beta2
* Chrome Version 92.0.4515.131 (Official Build) (64-bit)
* MariaDB 10.6.3-1, PHP Version 8.0.9 
* Arch Linux Kernel 5.13.7

**Comment by johnM2401** [comment]
Hey @romleinster 

I have given this a try in the full release of SuiteCRM8

Please let us know if you are able to try this now, and if you are still having this issue

Thanks for raising this!

**Comment by romleinster** [comment]
hey thanks for the reply. I just got the full 8.0 version installed.

I'm seeing similar behavior - when I click Fields in the edit Products pane of the studio, nothing happens. I'm not getting anything logged to the php error log but I see in console two lines:


POST https://lethe.asuscomm.com/suitecrm8/legacy/index.php?to_pdf=1&sugar_body_only=1&module=ModuleBuilder&action=modulefields&view_package=studio&view_module=AOS_Products 500 (Internal Server Error)

**Comment by johnM2401** [comment]
Hey there, 

Thanks for getting back in touch!


I've given this another try with your newly added info, it looks as though this *may* be an issue when using PHP 8

I am unable to access Studio->Products->Fields when using PHP 8.0

However, PHP 7.3 appears to be fine for me.


Would it be possible for you to check this in a lower PHP version, to help confirm?

(Either way, I'll mark this as a Bug for now)

**Comment by romleinster** [comment]
Confirmed, I can add fields successfully using php 7.3.32. Thanks again for following up. 

I'm seeing "Undefined" a lot in the interface and a lot of "Failed to load resource/404" errors for suitecrm8/legacy/cache/jsLanguage/en_us.js?v=lGo3tH4bqAf6Wv-QN2taLg in console. Not sure if these are related or a separate issue
![Screenshot 2021-12-13 095054](https://user-images.githubusercontent.com/8878992/145836022-18d71f98-c5ac-4d67-857f-16add5157354.png)
![Screenshot 2021-12-13 095240](https://user-images.githubusercontent.com/8878992/145836023-e7ae80fd-21d5-43c6-a87d-c06df43ff52e.png)
.

**Comment by johnM2401** [comment]
Hey, 

That's great to hear.

Thank you for taking the time to confirm that you have success with PHP 7.3

This does indeed seem to be a bug with PHP 8.0, then.

Thanks again!
