### ISSUE TITLE
Suite8 Performance Issues with >1k records

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM-Core#112]
#### Issue

Initially noted by a forum user, sakman, on this forum post: 
https://community.suitecrm.com/t/excessive-page-load-times-after-selecting-view-accounts/85268/2

It appears that the CRM performance dramatically decreases, if the user has a larger amount of data.
<br>

#### Expected Behavior

While performance hits are expected for large amounts of data, the performance hit should not be so severe for such an amount of data.
<br>

#### Actual Behavior

The CRM Performance degrades for a larger amount of data.

For example, locally, I have ~1200 records on Accounts

The accounts Listview can take anywhere from 5 to 30 seconds to load, and Pagination on the Listview can be even longer.

Strangely, this issue seems to ONLY be on the Suite8 Desktop View.

This issue does not appear on Mobile view, nor on the Classic View for the Module.
<br>

#### Possible Fix

Unsure
<br>

#### Steps to Reproduce

1. Create a large number of records for a Suite8 Module. (ie, around 1k)
2. Navigate to the Listview of this Module, and monitor Load times
3. Compare this to the load times for other modules, where fewer records exist.

<br>

#### Context

Performance is heavily affected, so usability is too.
<br>

#### Your Environment

* SuiteCRM Version used: 8.1.2 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 87.0.4280.88 & Firefox 100.0.2 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4, MariaDB 10.2.23, SuiteCRM 8.1.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by suz-vdk** [comment]
I have this exact issue in 8.7
