### ISSUE TITLE
installing check mentions errors while there is only one yellow warning

### ISSUE THREAD

**Issue by f1-outsourcing** [salesagility/SuiteCRM-Core#120]
v8.1.2

![20220627-113335-check-red](https://user-images.githubusercontent.com/13450219/175909572-b843aade-94dd-4720-904c-aa94604aa4ee.png)

**Comment by johnM2401** [comment]
Hey

I believe you still get the prompt, as these items are important to the CRM's functionality.

However, you should be able to ignore these items by checking the "Ignore System Check Warnings" checkbox, and proceeding with the install.

I'm going to close this item as, from your other issues, you seen to have completed the install so are no longer blocked by this.

However, please let us know if you feel there is a bug here to be addressed.


Thanks!

**Comment by f1-outsourcing** [comment]
No. It is not consistent, red is error, yellow is warning (as you use this) you have to change the error handling here. Different colour different message.
