### ISSUE TITLE
install form does not check on trailing slash at domain

### ISSUE THREAD

**Issue by f1-outsourcing** [salesagility/SuiteCRM-Core#123]
v8.1.2 zip

install form does not check on trailing slash at domain, resulting in a incorrect string of RewriteBase on line 22 in public/legacy/.htaccess

```
     19     Options -Indexes
     20     Options -MultiViews
     21     RewriteEngine On
     22     RewriteBase crm.example.comlegacy/
     23     RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&modulename=app_strings&lang=$1 [L,QSA]
     24     RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&modulename=$1&lang=$2 [L,QSA]
     25

```

**Comment by f1-outsourcing** [comment]
I had to remove the crm.example.com to get rid of the error pages

**Comment by f1-outsourcing** [comment]
You still have to update the code!!!!

**Comment by johnM2401** [comment]
Hey @f1-outsourcing 

As far as I'm aware, the rewrite base value will build based on the site_url of the CRM.
So, from the information available here, this looks to be just an issue with the site_url value. (in public/legacy/config.php)

However, If you feel there is still a valid bug with the CRM here, please feel free to raise a new issue.

If you do so, please fill in the New Issue form as much as is possible, to allow us to identify / diagnose these issues.

Thanks!

**Comment by f1-outsourcing** [comment]
???

Your code generates this line in a htaccess, the 

`RewriteBase crm.example.comlegacy/`

This normal quality of coding suitecrm, to just ignore this? If this form value is not correctly checked this will always generates errors how many people are entering a trailing / ?
The alternative is it comes not from the form, and it will always generate this error.
Maybe you should have someone experienced look this?
