### ISSUE TITLE
Configure Module Menu Filters  doesn't work with error message "There is no action by that name: Wizard"

### ISSUE THREAD

**Issue by sangele** [salesagility/SuiteCRM-Core#128]
#### Issue
In the admin section "Module setting", when I click on [Configure Module Menu Filters] link (/#/studio/wizard?wizard=StudioWizard&option=ConfigureGroupTabs), the result page displays an error : "There is no action by that name: Wizard".

#### Expected Behavior
It should display the screen to edit the menu.

#### Actual Behavior
There is only one message : ""There is no action by that name: Wizard".

Here is the log 
[FATAL] Exception handling in /public/legacy/include/MVC/Controller/SugarController.php:397
[FATAL] Exception in Controller: There is no action by that name: Wizard

#### Steps to Reproduce
1. Log into SuiteCRM
2. Click on "Admin" link in the menu below your name
3. Go to ""Module setting"
4. Click on [Configure Module Menu Filters] : /#/studio/wizard?wizard=StudioWizard&option=ConfigureGroupTabs

#### Context
High priority because it's not possible to configure the menu.

#### Your Environment
* SuiteCRM Version used: 8.0.4
* Browser name and version : Chrome Version 100.0.4896.127 (Build officiel) (x86_64)
* Environment name and version : PHP 7.4, MySQL

**Comment by johnM2401** [comment]
Hey

Thank you for getting in touch!

I'm closing this issue for now, as I appear to be able to access the Module Menu Filters page on the most recent version of SuiteCRM8
(8.2.3 at time of writing)

![image](https://user-images.githubusercontent.com/13675281/216608577-cb2953ac-38cf-4dd0-8a0b-2ea5f1f604af.png)

Checked in both PHP7.4 and PHP 8.0

If you are still experiencing this issue, please get in touch and I can re-investigate!

Thanks!

Also, for your future reference, there is another bug around this functionality, where saving appears to fail in PHP8: https://github.com/salesagility/SuiteCRM-Core/issues/46
