### ISSUE TITLE
Unable to rename module labels

### ISSUE THREAD

**Issue by jpblonshine** [salesagility/SuiteCRM-Core#139]
#### Issue
When attempting to rename a module, the system will not allow the save.

#### Expected Behavior
As an Admin User:
1) Navigate to the admin page 
2) Click on Rename Modules
3) Navigate to Project Module
4) Click Pencil to reveal the edit
5) Type in singular and plural module name
6) Click Save
7) Module appears with new name

#### Actual Behavior
As an Admin User:
1) Navigate to the admin page 
2) Click on Rename Modules
3) Navigate to Project Module
4) Click Pencil to reveal the edit
5) Type in singular and plural module name
6) Click Save
7) A blank screen appears

#### Context
By not being able to rename the module, our users get confused as Project is not a term used in our organization.

#### Your Environment
SuiteCRM Version: 8.1.2-6
Platform: AWS Debian Linux/Unix
PHP Version 8.0.20
Chrome Version 103.0.5060.114

### Error Output from Diagnostic
[Thu Jul 21 16:16:10.615353 2022] [authz_core:error] [pid 686:tid
140262080636672] [client ip_address:57932] AH01630: client denied by server
configuration: /opt/bitnami/phpmyadmin/index.php
[Thu Jul 21 16:34:43.772388 2022] [proxy_fcgi:error] [pid 70105:tid
140262072243968] [client ip_address:58797] AH01071: Got error 'PHP message:
PHP Warning: Undefined array key "error" in
/bitnami/suitecrm/public/legacy/cache/smarty/templates_c/%%4C^4CA^4CA03677%%Renam
eModules.tpl.php on line 51PHP message: PHP Warning: Undefined array key
"dropdown_name" in
/bitnami/suitecrm/public/legacy/cache/smarty/templates_c/%%4C^4CA^4CA03677%%Renam
eModules.tpl.php on line 61PHP message: PHP W [Thu Jul 21 16:34:58.419133 2022]
[proxy_fcgi:error] [pid 70105:tid 140262298846976] [client ip_address:58798]
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Non-static
method DropDownHelper::saveDropDown() cannot be called statically in
/bitnami/suitecrm/public/legacy/modules/Studio/wizards/RenameModules.php:808
Stack trace:
#0
/bitnami/suitecrm/public/legacy/modules/Studio/wizards/RenameModules.php(366):
RenameModules->changeAppStringEntries()
Press [Enter] to continue:
https://github.com/bitnami/vms/issues/1 /bitnami/suitecrm/pub

**Comment by johnM2401** [comment]
Hey Folks!

Closing this as it no longer appears to be an issue, tested in 8.2.3 and I'm able to Rename modules in PHP8

Changing Accounts to "renameTest"
![image](https://user-images.githubusercontent.com/13675281/216661626-d8720b12-cac7-4211-a772-e26090a15afc.png)
![image](https://user-images.githubusercontent.com/13675281/216661503-c9e09d19-178c-46e6-bc19-620f47c1e4c1.png)


8.2.0 appears to contain [this fix](https://github.com/salesagility/SuiteCRM/issues/9574) to the Rename Modules functionality.

<br>

If you're still having issues regarding Module Renaming, (or any other issues relating to SuiteCRM8), please don't hesitate to get in touch!
