### ISSUE TITLE
cron.php fails with "must be compatible" error from AOPInboundEmail.php

### ISSUE THREAD

**Issue by kgaillot** [salesagility/SuiteCRM-Core#143]
Trying to run cron.php with PHP 8 fails with a fatal error:

    PHP Fatal error:  Declaration of AOPInboundEmail::handleCreateCase(Email $email, $userId) must be compatible with InboundEmail::handleCreateCase($email, $userId)

#### Issue

I installed SuiteCRM 8.1.2 in the environment described below. It appeared to do a legacy install even though everything went smoothly; I'm not sure whether that's expected. I ran public/legacy/cron.php manually and got the above fatal error.

#### Expected Behavior

cron.php can be run without errors

#### Actual Behavior

cron.php generated fatal error mentioned above

#### Possible Fix

See PR salesagility/SuiteCRM#9729 

#### Steps to Reproduce

The issue was consistently reproducible in the environment described below. PHP 8 appears to be the key factor. I can give a detailed list of steps needed to install in that environment if needed.

#### Context

This prevents cron.php from running successfully in the environment below.

#### Your Environment

* SuiteCRM Version used: 8.1.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n/a
* Environment name and version (e.g. MySQL, PHP 7):
  * MariaDB 10.5.16
  * PHP 8.0.21 (from remi repo, so IMAP support is built in)
  * Apache HTTP Server 2.4.54
  * PHP-FPM 8.0.22
* Operating System and version (e.g Ubuntu 16.04): Fedora 35

**Comment by johnM2401** [comment]
Hey!

Thanks for raising this issue as well as providing us with a fix!

Closing this as associated fixes have been merged into 8.2.1, and issues have been resolved:
https://docs.suitecrm.com/8.x/admin/releases/8.2/


Thank you, again!
