### ISSUE TITLE
Database port on install

### ISSUE THREAD

**Issue by ROBJkE** [salesagility/SuiteCRM-Core#16]
#### Issue
Seems that there is no way to change the database port on the install process `bin/console suitecrm:app:install` at the moment.   
I run different databases on custom ports so it is necessary to change it.

#### Expected Behavior
A possibility to change the database port on install routine

#### Actual Behavior
Uses 3306 anyway

#### Possible Fix
Try to set the port manually in `.env.local` but then can't force the install process again because this file exists

#### Context
I run a DB in seperate Docker Container on non standard port.  
I think I am not the only one with such a setup so this is a medium-high priority issue i guess

#### Your Environment
- App runs in Alpine 3.14 + PHP 8.0 + nginx 1.20. Container
- MariaDB 10.x runs in another container
- SuiteCRM 8 Beta 3

**Comment by brett-stanley** [comment]
@ROBJkE same here. I passed the nonstandard port in the DBHOST parameter for installation, but it still appended :3306 to it in the .env.local file

my server: 192.168.2.57:53306
entry in .env.local: 192.168.2.57:53306:3306

**Comment by johnM2401** [comment]
Hey

For reference, it seems that in the file: 
**`......./core/backend/Install/Command/LegacyInstallCommand.php`**

At ~line 105, the db_port is not marked as required:
```
        $this->inputConfig['db_port'] = [
            'question' => new Question('Please enter the db port: ', '3306'),
            'argument' => new InputOption(
                'db_port',
                'Z',
                InputOption::VALUE_REQUIRED,
                'database port'
            ),
            'default' => '3306',
            'required' => false
        ];

```

So it won't show as a parameter in the install script.

You should be able to amend this by changing " 'required' => false " to " 'required' => true "

Or by passing the -Z parameter, when passing all parameters manually


Please let us know if you have any issues with this, (like noted by Brett-stanley above), or need any further information!

Thanks!

**Comment by ROBJkE** [comment]
since release version its possible to enter the db port via cli / browser install.
so this issue is solved
