### ISSUE TITLE
Contact Email Address not showing in Subpanels

### ISSUE THREAD

**Issue by BrianRisden** [salesagility/SuiteCRM-Core#168]
#### Issue

Contact email address does not show in subpanels under opportunities or accounts. 
#### Expected Behavior

Contact email address should show in subpanel if there is an email in the contacts
#### Actual Behavior

The email column is blank.

#### Possible Fix

Might be related to this issue. 
https://github.com/salesagility/SuiteCRM-Core/issues/100

#### Steps to Reproduce

1. Use the demo and click on any Opportunity or Account.
2. Click on the contact subpanel. 
3. All email columns are blank. 
<img width="1146" alt="Screen Shot 2022-10-17 at 11 03 08 AM" src="https://user-images.githubusercontent.com/64560963/196214911-a9e40560-4a7a-44e8-8b69-77718f0c71e3.png">
<img width="1100" alt="Screen Shot 2022-10-17 at 11 02 56 AM" src="https://user-images.githubusercontent.com/64560963/196214935-b404addf-f19e-42be-a929-c6fd7f90a2a9.png">

#### Your Environment

* SuiteCRM Version used: 8.2.0, Also the demo on version 8.1.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 105.0.5195.125 (Official Build) (x86_64)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7.23-23, PHP 7.3.33
* Operating System and version (e.g Ubuntu 16.04):

**Comment by orokteo** [comment]
With are waiting for this correction.
Can we have an estimation in which will it be corrected .
If not, is there any way to have the information with a speficic manipulation in studio ?

**Comment by J-Wick4** [comment]
Version 8.4.0 and this bug persists. :(

**Comment by sasotech** [comment]
Version 8.4.1 also same bug.

**Comment by Stejcek** [comment]
Version 8.5.0 same bug.

**Comment by chris001** [comment]
Results of Team Investigating would be appreciated...

**Comment by azzy9** [comment]
I did come up with this fix which seems to work, just doesn't look too clean to submit as a PR:
https://community.suitecrm.com/t/no-emails-shown-in-subpanel-contact-for-accounts/90915/9

**Comment by chris001** [comment]
Without a PR, it may never get fixed for a long time!  If the fix works, why not submit PR for benefit of all?  If dev team feel it doesn't look too clean, they can clean it, then merge it.

**Comment by Stejcek** [comment]
> I did come up with this fix which seems to work, just doesn't look too clean to submit as a PR: https://community.suitecrm.com/t/no-emails-shown-in-subpanel-contact-for-accounts/90915/9

Thank you for your help and I confirm that the fix is working for version 8.5.0.

**Comment by chris001** [comment]
I made a Pull Request to fix this bug, thanks @azzy9 
https://github.com/salesagility/SuiteCRM-Core/pull/417
