### ISSUE TITLE
SuiteCrm 8.2 : logged out pb

### ISSUE THREAD

**Issue by cgodard95** [salesagility/SuiteCRM-Core#172]
#### Issue

In SuiteCrm 8.2.0 logged out does'nt work

#### Steps to Reproduce

1. Click on Administrator>Logout
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 8.2.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 105.0
* Environment name and version (e.g. MySQL, PHP 7): Php 8.0.19
* Operating System and version (e.g Ubuntu 16.04): Debian 10 Buster

**Comment by pgorod** [comment]
Thanks @cgodard95, if this is a duplicate I guess we can close 👍
