### ISSUE TITLE
Suite CRM 8.2.0: Displayed Columns not working

### ISSUE THREAD

**Issue by JayP1203** [salesagility/SuiteCRM-Core#174]
Suite CRM 8.2.0 is not adding columns properly to be displayed.

![image](https://user-images.githubusercontent.com/55115618/198720258-1d880312-b4b5-4750-9534-4872b189f878.png)

Not being dispalyed:

![image](https://user-images.githubusercontent.com/55115618/198720428-adddcdf2-e0a6-4b0f-9dbe-5d790dd5db2f.png)

How it works/looks in Version 7 (As you can see, some of the columns are smaller in length, depending on the wrapping of the text or text character length):

![image](https://user-images.githubusercontent.com/55115618/198720929-8d3aa242-7711-4c9f-9421-8aa5936f9d93.png)

All are displayed:

![image](https://user-images.githubusercontent.com/55115618/198721274-94f8d468-20ec-4579-be01-cd13664a313e.png)

**Comment by JayP1203** [comment]
Wondering if anyone has had a chance to review this request??

**Comment by clemente-raposo** [comment]
Hi @JayP1203, we are working on this issue, it should come on one of the next releases

**Comment by JayP1203** [comment]
@clemente-raposo Thank you for getting back to me, hopefully we can see this fix sooner rather than later!

**Comment by lukio** [comment]
@clemente-raposo if you are working on this issue, and you will create a pull request I can test it. It seems that the number of columns are hard-coded.

**Comment by lukio** [comment]
Same as #252. We can closed it.
