### ISSUE TITLE
Invalid CSRF token

### ISSUE THREAD

**Issue by kingfisher77** [salesagility/SuiteCRM-Core#180]
#### Issue

**Excerpt from SuiteCRM Forum** 
https://community.suitecrm.com/t/invalid-csrf-token/86806
While working with SuiteCRM, I get errors of type: Invalid CSRF token. It is a POST 403 graphql problem according to the browser’s tools. Network scanning reveals that Requested Cookie is NOT the one that Response sends back! Log file more or less say the same...

#### Expected Behavior

Use SuiteCRM without errors.

#### Actual Behavior

Frequent Invalid CSRF token errors which leads to interruption in Frontend, browser reload is necessary until next error after few klicks.

#### Possible Fix

Core hack: https://community.suitecrm.com/t/invalid-csrf-token/86806/3

#### Steps to Reproduce

1. Install SuiteCRM 8.2. (in my case Bitnami Docker, but there are reports in forum for other operation modes
2. Invalid CSRF token errors appear

#### Context

See above

#### Your Environment

- SuiteCRM 8.2.1
- Bitnami Docker

**Comment by vincentkersten** [comment]
+1

After updating 7.12 series to 8.2.1, I also have Invalid CSRF token issues, reported in the prod.log. 
Both suite 7 and 8 sessions variables are correctly configured, to no avail (https://docs.suitecrm.com/8.x/admin/configuration/sessions-configuration/#_option_2_changing_session_dir_in_suitecrm_configuration , option2). 

Only by removing the CSRF check (core hack, see OP) makes Suite8 work.

**Comment by ps-mzamette** [comment]
We are experiencing the same issue with SuiteCRM 8.2.1 (PHP 7.4). This blocks us from upgrading to 8.2. 😞

**Comment by stefanomarty** [comment]
I'm having this same issue after upgrading from 8.2.1 (which was running ok) to 8.2.2

I tried patching \core\backend\Security\CSRFValidationListener.php by commenting out line 96. That made the login possible again, but with no menu at all (just logout), so I had to go back to 8.2.1 from backup.

These CSRF token errors are mentioned by many users, maybe this issue needs to be addressed more thoroughly. Just my 2¢.

**Comment by olivierlambert** [comment]
I can confirm the issue. I'm hitting it after updating from 8.2.1 to 8.2.2.

Exact same behavior than @stefanomarty (no menu etc.)

**Comment by ilmoralito** [comment]
I experience the same problem. How to rollback to version 8.2.1?

**Comment by stefanomarty** [comment]
> I experience the same problem. How to rollback to version 8.2.1?

Well, it depends on how you handle your installation, I usually make a full backup (folder.tar.gz + DB.sql) right before upgrading. If something's wrong, I delete the upgraded folder+DB and restore the old ones from backup.

A better solution would be to run a separate instance+db (copied on the fly from prod), upgrade that instance and test it, then upgrade the prod instance only if the tests are ok. Actually that should be done by developers before releasing the upgrade, but you cannot always get all the bugs...

Without a backup you probably need to re-install the previous version, but if the upgrade process changed the DB structure you could have problems with the previous version's SQL. I don't know, never tried that way, sorry.

This could help:
https://docs.suitecrm.com/8.x/admin/installation-guide/upgrading/

**Comment by olivierlambert** [comment]
Personally, I did the same process for an update and it worked (8.2.2 to 8.2.1). I think because no big changes were made on the database.

**Comment by ilmoralito** [comment]
In my case I have migrated from version `7.10.11` to `8.2.2`. When completing the official guide I have tried to log in I get this behavior. By applying the solution to comment line 96 `core/backend/Security/CSRFValidationListener.php` allows access to the site, but the menu is not there, just logout. If I manually access administration, the page appears empty. Also in the console in one of the calls to `/api/graphql` I get the following message
```
{
      "mistakes": [
          {
              "message": "Internal server error",
              "extensions": { "category": "internal" },
              "locations": [{ "line": 2, "column": 3 }],
              "path": ["appMetadata"]
          }
      ],
      "data": { "appMetadata": null }
}
```
I have tried migrating from `7.12.8` to `8.2.0` and `8.2.1` and get the same behavior

```
ubuntu 22.04
Apache/2.4.52
PHP 7.4.33
mysql5.7
```

**Comment by stefanomarty** [comment]
Ok, if you followed the official guide you should have a backup of the code folder and the database. I'd suggest not to delete your current upgraded code+DB, just rename the folder and the DB (use PhpMyAdmin or the CLI to something like suitecrm.8.2.2 and same for the DB.  If a solution comes for the CSRF problem, you can test it on this bundle later.

Restore the code in the original folder, and restore the DB: you should be running again SuiteCRM with your old 7.12.8

Later you can test the new version on the renamed code folder, by pointing Apache to it or, if possible, creating a new vhost pointing to it. You'll have to change the the DB name in the config file in the renamed folder:
`public/legacy/config.php`
in order to use the renamed DB, also check there's no reference to the DB in
`public/legacy/config_override.php`

See here:
https://community.suitecrm.com/t/how-to-change-database-settings-for-a-cloned-suitecrm-instance/39398

It should work for you version 7.12.8

**Comment by Quent1L** [comment]
I am using version 8.2.1.
The core hack works but I still get the error "Error occurred while saving record" even though the call to the graph API was successful (HTTP status 200). Why and is it possible to remove it temporarily (until this bug is patched)?

**Comment by sebastianbrosch** [comment]
I got this error message after adding a E-mail address to a contact and saving. SuiteCRM shows the error message "Error occurred while retrieving records" and is loading until refresh.

I got this error message in the logs (`/logs/prod/prod.log`):
```
[2023-01-10 07:37:59] request.INFO: Matched route "api_graphql_entrypoint". {"route":"api_graphql_entrypoint","route_parameters":{"_route":"api_graphql_entrypoint","_controller":"api_platform.graphql.action.entrypoint","_graphql":true},"request_uri":"http://XXXXXXXXXX/api/graphql","method":"POST"} []
[2023-01-10 07:37:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Invalid CSRF token" at /bitnami/suitecrm/core/backend/Security/CSRFValidationListener.php line 96 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Invalid CSRF token at /bitnami/suitecrm/core/backend/Security/CSRFValidationListener.php:96)"} []
```

I'm using the [Bitnami Docker Image for SuiteCRM](https://hub.docker.com/r/bitnami/suitecrm).

**Comment by olivierlambert** [comment]
Hello @jack7anderson7 

Thanks for the fix! Will it be released in maybe a 8.2.3?

**Comment by clemente-raposo** [comment]
Hi @olivierlambert,

Yes it has been just released on 8.2.3.

**Comment by olivierlambert** [comment]
You rock, testing that ASAP!

**Comment by clemente-raposo** [comment]
@kingfisher77 @olivierlambert @sebastianbrosch @Quent1L @stefanomarty @ilmoralito @ps-mzamette 

Just a couple of notes on this issue.

## Possible causes for this issue

#### 1. previous errors
We found that you can get the Invalid XSRF token if there were errors on a previous request, which caused the invalidation of the token. In this cases the issue to fix is the one on the previous requests.

To find the issue: 
- Open the browser dev tools
- Go the network tab
- Check the graphql requests responses to see if any contains an "errors" entry
- if more details are needed edit `.env.local` and set `APP_ENV=qa` this should provide more info on the `errors` entry

#### 2. php 8 support
This partly related with the above but many of the errors we found were related with the php 8 support of the legacy side. We've tried to fix all the ones we found. However, the php 8 support is still a work in progress. We have been testing with php8.1 and php 8.2 and hopefully we will be able to get those versions fully supported soon.  

#### 3. Wrong XSRF Token re-generation
This I think is the true problem reported on this issue.
We were able to replicate it, but did not find a consistent, step-by-step, way to replicate. 
 
What was happening was that when there were multiple simultaneous graphql request where some outlived the others. There would be one of the requests that regenerated the XSRF Token. But the others would still keep the old token. Making one or more requests to fail. 

As mentioned before, we did not have a consistent step-by-step way to reproduce the issue, though we were eventually able to replicate and check that the issue fix work by swapping between the version with the code and the one without.

However, given that we don't have a consistent way to reproduce, we would like to ask you that if you still have this issue please let us know.

**Comment by Quent1L** [comment]
Thanks @clemente-raposo 

I have just done the update (from 8.2.1 to 8.2.3)
The HTTP graphql requests are no longer in error (status 200 in the "Networks" tab of devtools) but I still get the following error message: "Error occurred while saving record".

I have no error in the prod.log file.
I have this as an error in suitecrm.log but it has been there for a long time so I don't think it's related.
`[ERROR] Unable to find relationship projects_contacts_resources`
`[ERROR] Unable to find relationship am_projecttemplates_contacts_resources`

I tried to empty the cache with the following commands: 
```
bin/console cache:clear
rm -rf cache
rm -rf public/legacy/cache

```
Do other similar commands exist?

**Comment by clemente-raposo** [comment]
Hi @Quent1L

Could you please try the following:

- edit the .env.local file and set APP_ENV=qa
- run php bin/console cache:clear
- Open the devtools of your browser
. clear the network tab
- refresh the page or do the action you were trying (ti was save right)
- Check if there are any request with 500 or 401
- Check the graphql requests response (even the ones with 200). See if there are any that have an "errors" entry on the json that comes on the response)

**Comment by Quent1L** [comment]
Thank you for your answer @clemente-raposo

I answer you here but maybe it would be better to create a new GitHub issue?

You are right, a graphql HTTP request comes back with a status of 200 but with an error in response 

`{
    "errors": [
        {
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "saveRecord"
            ]
        }
    ],
    "data": {
        "saveRecord": null
    }
}`

Here is the answer when I switch to debug mode 

Status of the HTTP request : 500

![image](https://user-images.githubusercontent.com/92377389/215042111-b8712ab9-ab0f-47a5-9456-b05316e6d6b8.png)

The problem seems to come from my custom modules... I tried to deactivate this one "aff_Affaire" but the error was transferred to another one.

The order follows that described in the following file: _public/legacy/custom/application/Ext/Include/modules.ext.php_

Here is an extract of the code of this file:

```
 //WARNING: The contents of this file are auto-generated
$beanList['aff_Affaire'] = 'aff_Affaire';
$beanFiles['aff_Affaire'] = 'modules/aff_Affaire/aff_Affaire.php';
$moduleList[] = 'aff_Affaire';
```
What should I do?

**Comment by Quent1L** [comment]
I have tried, but I always get the same error

I have run the following command lines: 

To delete files with the extension `*.ext.php`
 - In custom folder: `find . -name "*.ext.php" -type f -delete`

To reset permissions
 - In public folder : `chmod -R o+rwx custom`

Then the quick repair and rebuild. The repair has recreated the files but the error persists 😔

**Comment by olivierlambert** [comment]
It seems that the upgrade to 8.2.3 fixed my issues, obviously needed both:
* `./bin/console suitecrm:app:upgrade -t suitecrm-8-2-3`
* `./bin/console suitecrm:app:upgrade-finalize -t 8.2.3`

Note: I initially forgot about the second one, and I had a broken display, but after running it, everything seems OK. I'll continue to use it during next week and report any weird behavior.

**Comment by Gendzi** [comment]
The fix didn't work for me, on release 8.2.3.
The simplest scenario:

1) Log in to the home page
2) wait 30+ minutes (35 to be sure), DO NOT anything
3) Click in the navigation panel to Accounts LV. (IF refresh current page, it looks like fix working and there is no logout)
...
Invalid CSRF token -> logout

**Comment by hector-chim** [comment]
Same Issue Here, Clean Install and getting Error occurred while fetching metadata

**Comment by Quent1L** [comment]
The fix with the 8.2.3 update works for me in part.

My SuiteCRM instance is configured with keycloak authentication (SAML) but as described in the documentation, native authentication can be accessed via the url `https://<your-suitecrm-instance>/auth`.
When I try to access this address I get a blank page with the error with the Invalid CSRF token

Hopefully this can help you to reproduce it

**Comment by joho1968** [comment]
I honestly don't understand how bugs like these can exist at version 7.x or 8.x of an application. 

I just did a fresh install and CLI-setup of 8.3.1 on Ubuntu 22.04.LTS / PHP 7.4-FPM / Apache ... after loading a number of things, it ends with this:

`{"@context":"\/suitecrm\/api\/contexts\/Error","@type":"hydra:Error","hydra:title":"An error occurred","hydra:description":"Invalid CSRF token"}`

The URL in the developer console is (POST) http://127.0.0.1/suitecrm/api/graphql

**Comment by conradbekondo** [comment]
> For me, this turned out to be caused by a non-default "session.name" PHP setting, as out lined here:
> 
> https://www.joho.se/2023/09/11/suitecrm-troubles-could-be-caused-by-non-default-session-name/

Where do I find these settings?

**Comment by conradbekondo** [comment]
the `/api/graphql` endpoint keeps returning this as response in version 8.5

```json
{
    "@context": "\/api\/contexts\/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Invalid CSRF token"
}
```

I don't know what I can do to fix this
