### ISSUE TITLE
PHP 8.2 - Upgrade is not working with php version 8.2

### ISSUE THREAD

**Issue by silikonski** [salesagility/SuiteCRM-Core#183]
#### Issue
I can not upgrade from 7.12.x version because migration script is limited to php 8.0 (security only version)

#### Expected Behavior
Recommended stable php version with support until December 2024 is php 8.2

#### Actual Behavior
When I start bash file a get this message "In XmlUtils.php line 50: Extension DOM is required." because i am running php 8.2 

#### Environment
Plesk Obsidian Version 18.0.49
CentOS 7
PHP 8.2
SuiteCRM 7.12.6

**Comment by TimmiORG** [comment]
Hi @silikonski 

according to the compatibility matrix 7.12.x is only supporting up to PHP8.0.
https://docs.suitecrm.com/admin/compatibility-matrix/#_suitecrm_7_12_x

The roadmap is saying PHP8.2 support will be part of SuiteCRM-7.14 and 8.4.
https://suitecrm.com/suitecrm-roadmap/

**Comment by silikonski** [comment]
OK, I see thank you. That is good news, I'll just have to wait.
