### ISSUE TITLE
[8.2.2] Bulk export of leads or contacts not working

### ISSUE THREAD

**Issue by TimmiORG** [salesagility/SuiteCRM-Core#184]
#### Issue
It looks like the bulk action on leads or contact page does not work. 
Nothing is happening when selecting the leads or contacts and select export in the bulk action menu.

#### Expected Behavior
Action of the bulk action selector will be executed

#### Actual Behavior
Nothing happen while pressing any bulk action.

#### Steps to Reproduce
1. Got to Leads
2. Select Leads
3. Perform any bulk action like export, PDF etc.

#### Context
Export function is used on various pages. For reporting etc.

#### Your Environment
* SuiteCRM Version used: 8.2.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 108
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP8.0
* Operating System and version (e.g Ubuntu 16.04): Rocky Linux 9

**Comment by scicali** [comment]
Have u try to refresh (F5) the page?

**Comment by TimmiORG** [comment]
Hi @scicali 

hmmm this is interesting.

I did the following:
1. select all
2. bulk action export -> nothing
3. reload the page (F5)
4. select all
5. bulk action export -> get the CSV file.

Still this does not sound right to me!

**Comment by scicali** [comment]
This happen after upgrade, sometimes. Once you've refreshed the page, issue disappeared. Like a cache issue

**Comment by TimmiORG** [comment]
Hi @scicali 

still I would consider this as a bug something does not get initialized correctly.

**Comment by johnM2401** [comment]
Hey!

I've given this a quick try, and I believe I can partly replicate this.

Upon installing 8.2.0
Initially, The Listview Bulk Actions appear to have issues, I cannot perform export/merge/delete/etc

However, If I reset the CRM's permissions & hard refresh as scicali noted, the Listviews return to normal behaviour across the CRM.

<br>

Would you be able to try re-setting Permissions across the CRM, Hard Refreshing Browser, and letting us know if this returns functionality for you?

Thanks!

**Comment by TimmiORG** [comment]
Hi @johnM2401 

I'm running 8.2.2 on my test platform so no issue to perform this.
Please explain what you mean with re-setting Permissions across the CRM.
File permissions or something through the GUI?

**Comment by johnM2401** [comment]
Hey @TimmiORG 

Thank you for your time!

Apologies, I'm meaning re-setting File Permissions.

For SuiteCRM8, we typically recommend running the following permissions commands:

```
find . -type d -not -perm 2755 -exec chmod 2755 {} \;
find . -type f -not -perm 0644 -exec chmod 0644 {} \;
find . ! -user www-data -exec chown www-data:www-data {} \;
chmod +x bin/console
``` 

(Replacing www-data with your webserver's User/Group Name)
[(Docs on Permissions can be found here)](https://docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing/#_2_3_set_permissions)

Thanks!

**Comment by TimmiORG** [comment]
Hi @johnM2401 

sure no issue.

I have set the file permissions as requested and run the page in private mode with disabled cache.
The leads export was working. Contacts was only working after hitting refresh after the first try.

So the behaviour is still the same. Once I have performed the refresh and the second export it is working all the time.

**Comment by johnM2401** [comment]
Great!
Thank you again!

Perhaps some strange combination of Permissions & Browser Caching, then.

I'll reduce this bug's severity from Critical to Important, as it is possible to return the CRM's functionality.

Though I agree, ideally, this should behave normally without needing intervention.

Thank you again for your assistance!

**Comment by smh30** [comment]
We are also seeing this issue with all Bulk Actions not working unless the page is refreshed first. It was reported by a client who we recently upgraded from 7.10. 

**Your Environment**
    SuiteCRM Version used: 8.2.4
    Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 113, Chrome 114
    Environment name and version (e.g. MySQL, PHP 7): MySQL8, PHP8.1
    Operating System and version (e.g Ubuntu 16.04): Linux
