### ISSUE TITLE
SAML configuration not working 

### ISSUE THREAD

**Issue by simao-silva** [salesagility/SuiteCRM-Core#187]
#### Issue

I have followed the [official documentation](https://docs.suitecrm.com/8.x/admin/configuration/saml-configuration/) on how to configure SAML without success. No matter what I do, the login page does not redirect to the SAML provider and always shows the native SuiteCRM login. 
This is my `.env.local` file: 
```
SUITECRM_DATABASE_HOST=mariadb
SUITECRM_DATABASE_PORT_NUMBER=3306
SUITECRM_DATABASE_USER=******
SUITECRM_DATABASE_NAME=suitecrm
SUITECRM_DATABASE_PASSWORD=******
ALLOW_EMPTY_PASSWORD=no
SUITECRM_USERNAME=******
SUITECRM_PASSWORD=******

AUTH_TYPE=saml
SAML_USERNAME_ATTRIBUTE=username
SAML_USE_ATTRIBUTE_FRIENDLY_NAME=false
SAML_SP_CERT=MII******
SAML_SP_PRIVATE_KEY=MIIE******
SAML_AUTO_CREATE=enabled
```
And this my `hslavich_onelogin_saml.yaml` file located at `/bitnami/suitecrm/extensions/custom/config/packages/`: 
```
hslavich_onelogin_saml:
  # Basic settings

  idp:
    # entity id of your idp
    entityId: 'https://<KEYCLOAK URL>/auth/realms/master'  # e.g.: 'http://saml-idp-host/realms/master'


    singleSignOnService:
      # single sign on url your IDP
      url: 'https://<KEYCLOAK URL>/auth/realms/master/protocol/saml' # e.g.: 'http://saml-idp-host/realms/master/protocol/saml'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

    singleLogoutService:
      # single logout service url of your IDP
      url: 'https://<KEYCLOAK URL>/auth/realms/master/protocol/saml' # e.g.: 'http://saml-idp-host/realms/master/protocol/saml'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

    # IDP certificate
    x509cert: 'MIICmzCCA*************************************' # e.g. 'MIICmzCCAYMCBgGC1LTnr ... =''


  # The SP in this case is your SuiteCRM instance
  sp:

    # SP entity id. Use your SuiteCRM instance url
    entityId: 'https://<SUITECRM URL>' # e.g. 'https://<your-suitecrm-instance>'

    assertionConsumerService:
      # The path to SuiteCRM's acs service
      url: 'https://<SUITECRM URL>/saml/acs'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'

    singleLogoutService:
      # The path to SuiteCRM's SAML logout service
      url: 'https://<SUITECRM URL>/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

    # SuiteCRM's private key for SAML (sp)
    privateKey: '%env(SAML_SP_PRIVATE_KEY)%' # e.g. 'MIIEoAIBAAKCAQEAx ...'

    # SuiteCRM's certificate for SAML (sp)
    x509cert: '%env(SAML_SP_CERT)%' # e.g. 'MIIC1zCCAb8CBgGC1awPM ... ='


  # Optional settings

  # SuiteCRM's base url for SAML
  baseurl: 'https://<SUITECRM URL>/saml'

  ######
  # NOTE : The values for the following settings will depend on how the IDP is setup
  ######
  strict: true
  debug: true
  security:
    nameIdEncrypted: false
    authnRequestsSigned: true
    logoutRequestSigned: true
    logoutResponseSigned: false
    wantMessagesSigned: false
    wantAssertionsSigned: false
    wantNameIdEncrypted: false
    requestedAuthnContext: false
    signMetadata: false
    wantXMLValidation: true
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
  contactPerson:
    technical:
      givenName: 'Tech User'
      emailAddress: 'techuser@example.com'
    support:
      givenName: 'Support User'
      emailAddress: 'supportuser@example.com'
  organization:
    en:
      name: 'Example'
      displayname: 'Example'
      url: 'http://example.com'
```

#### Expected Behavior

The login page should redirect to my identity provider (Keycloak).

#### Actual Behavior

The login page shows the native SuiteCRM login.

#### Steps to Reproduce

1. Do the configurations on the official documentation
2. Access the SuiteCRM URL

#### Your Environment

* SuiteCRM Version used: 8.2.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 108.0.5359.124 and Firefox 108.0.1
* Environment name and version (e.g. MySQL, PHP 7): [Bitnami docker image](https://hub.docker.com/r/bitnami/suitecrm) with MariaDB 10.6
* Operating System and version (e.g Ubuntu 16.04): Debian 11

**Comment by clemente-raposo** [comment]
Hi @simao-silva ,

Thank you for reporting this issue. 

I noticed you have the SAML_AUTO_CREATE set to enabled.

That requires configuring the field mapping between the saml reponse and user fields. There are some instructions here: [Configuring user auto creation](https://docs.suitecrm.com/8.x/admin/configuration/saml-configuration/#_configuring_user_auto_creation)

Have you added this mapping t saml.yaml, which should looks similar to the following:

File: extensions/<your-package>/config/services/saml/saml.yaml

```
parameters:
  saml.autocreate.attributes_map:
    email: email1
    'urn:oid:2.5.4.4': last_name
    'urn:oid:2.5.4.42': first_name
```

**Comment by simao-silva** [comment]
Hi,

I was indeed forgetting the mapping in **saml.yaml**.  After adding that and clear the cache I am redirected to Keycloak but got the error *Invalid Request* and the logs show the following:
```
type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=172.21.0.1, error=client_not_found, reason=Cannot_match_source_hash
```

Do you know what it could be or do you have a Keycloak configuration sample on how the configuration should be?

**Comment by TimmiORG** [comment]
@simao-silva 
I just configured Suite8 and Keycloak.

I would advice to perfrom the testing without keys to sign the requests as this makes the debugging a bit fast.

Did you run 
`bin/console cache:clear`
To activate the AUTH change?

**Comment by simao-silva** [comment]
@TimmiORG Yes, I did. I also tried to set up using Keycloak v20 without success. Can you describe your steps or export your realm settings and share it?

**Comment by simao-silva** [comment]
@TimmiORG  I am using the same version of SuiteCRM and Keycloak as you. I followed your advice and disabled the signing. Here are the current configurations:
<details><summary>extensions/custom/config/packages/hslavich_onelogin_saml.yaml</summary>

```
hslavich_onelogin_saml:
  # Basic settings

  idp:
    # entity id of your idp
    entityId: 'https://keycloak.crm-test.example.com/realms/master'

    singleSignOnService:
      # single sign on url your IDP
      url: 'https://keycloak.crm-test.example.com/realms/master/protocol/saml'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

    singleLogoutService:
      # single logout service url of your IDP
      url: 'https://keycloak.crm-test.example.com/realms/master/protocol/saml'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

    # IDP certificate
    x509cert: 'MIICnzCCAY......ljnnDnk'

  # The SP in this case is your SuiteCRM instance
  sp:

    # SP entity id. Use your SuiteCRM instance url
    entityId: 'crm-test' # Have also tried https://crm-test.example.com

    assertionConsumerService:
      # The path to SuiteCRM's acs service
      url: 'https://crm-test.example.com/saml/acs'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'

    singleLogoutService:
      # The path to SuiteCRM's SAML logout service
      url: 'https://crm-test.example.com/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

    # SuiteCRM's private key for SAML (sp)
    privateKey: '%env(SAML_SP_PRIVATE_KEY)%' # e.g. 'MIIEoAIBAAKCAQEAx ...'

    # SuiteCRM's certificate for SAML (sp)
    x509cert: '%env(SAML_SP_CERT)%' # e.g. 'MIIC1zCCAb8CBgGC1awPM ... ='


  # Optional settings

  # SuiteCRM's base url for SAML
  baseurl: 'https://crm-test.example.com/saml'

  ######
  # NOTE : The values for the following settings will depend on how the IDP is setup
  ######
  strict: true
  debug: true
  security:
    nameIdEncrypted: false
    authnRequestsSigned: false
    logoutRequestSigned: false
    logoutResponseSigned: false
    wantMessagesSigned: false
    wantAssertionsSigned: false
    wantNameIdEncrypted: false
    requestedAuthnContext: false
    signMetadata: false
    wantXMLValidation: false
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
  contactPerson:
    technical:
      givenName: 'Tech User'
      emailAddress: 'techuser@example.com'
    support:
      givenName: 'Support User'
      emailAddress: 'supportuser@example.com'
  organization:
    en:
      name: 'Example'
      displayname: 'Example'
      url: 'http://example.com'
```

</details>

<details><summary>.env.local</summary>

```
DATABASE_URL="mysql://USERNAME:PASSWORD@mariadb:3306/suitecrm"

AUTH_TYPE=saml

SAML_USERNAME_ATTRIBUTE=username
SAML_USE_ATTRIBUTE_FRIENDLY_NAME=false

SAML_AUTO_CREATE=enabled
```

</details>


<details><summary>extensions/custom/config/services/saml/saml.yaml</summary>

```
parameters:
  saml.autocreate.attributes_map:
    email: email1
    'urn:oid:2.5.4.4': last_name
    'urn:oid:2.5.4.42': first_name
```

</details>

<details><summary>Keycloak</summary>


![Screenshot from 2023-01-31 01-14-02](https://user-images.githubusercontent.com/37107350/215633950-a28eecf9-8d1a-4888-8a0c-300ced6ab063.png)
![Screenshot from 2023-01-31 00-57-18](https://user-images.githubusercontent.com/37107350/215631762-e724ed70-b859-4fd0-bf77-c265e80e0e87.png)
![Screenshot from 2023-01-31 00-57-21](https://user-images.githubusercontent.com/37107350/215631765-4711f86a-305f-486f-b3dd-ece3428084c5.png)

* SAML Adapter settings:

```sh
<keycloak-saml-adapter>
    <SP entityID="https://crm-test.example.com"
        sslPolicy="EXTERNAL"
        logoutPage="SPECIFY YOUR LOGOUT PAGE!">
        <Keys>
            <Key signing="true">
                <PrivateKeyPem>PRIVATE KEY NOT SET UP OR KNOWN</PrivateKeyPem>
                <CertificatePem>
                    MIICnzCCAYcCBgGGBTun......LQLkYIIBgQY
                </CertificatePem>
            </Key>
        </Keys>
        <IDP entityID="idp"
             signatureAlgorithm="RSA_SHA256"
             signatureCanonicalizationMethod="http://www.w3.org/2001/10/xml-exc-c14n#">
            <SingleSignOnService signRequest="true"
                                 validateResponseSignature="false"
                                 validateAssertionSignature="false"
                                 requestBinding="POST"
                                 bindingUrl="https://keycloak.crm-test.example.com/realms/master/protocol/saml"/>
            <SingleLogoutService signRequest="true"
                                 signResponse="true"
                                 validateRequestSignature="false"
                                 validateResponseSignature="false"
                                 requestBinding="POST"
                                 responseBinding="POST"
                                 postBindingUrl="https://keycloak.crm-test.example.com/realms/master/protocol/saml"
                                 redirectBindingUrl="https://keycloak.crm-test.example.com/realms/master/protocol/saml"/>
        </IDP>
    </SP>
</keycloak-saml-adapter>
```

</details>

Right now, I am redirected to Keycloak but I immediately receive the error `Invalid Request`. Keycloak's logs show the following:
```
2023-01-31 01:03:50,978 WARN  [org.keycloak.events] (executor-thread-66) type=LOGIN_ERROR, realmId=73380795-2c8b-4880-921e-0f7a8d6c6f09, clientId=null, userId=null, ipAddress=***.***.***.***, error=client_not_found, reason=Cannot_match_source_has
```

From what you shared, the only thing that does match is the `PrivateKeyPem` in Keycloak. Did you manually set this value and, if so, where? I've tried to find some log files that could help debug this issues but I did not found any helpful.

**Comment by TimmiORG** [comment]
Hi @simao-silva 
I think best practise is not to use the master realm but OK. ;)

Please fix the extensions/custom/config/packages/hslavich_onelogin_saml.yaml
`entityId: 'crm-test' # Have also tried https://crm-test.example.com`

In Keycloak you call this "suitecrm"

The private key is fine. This is not shown in the export.

**Comment by simao-silva** [comment]
Hi @TimmiORG ,
I've changed the `entityId` to `suitecrm` and disabled `Client signature required`. Now I am redirected to Keycloak and able to authenticate. However, I am unable to go back to SuiteCRM dashboard:
![Screenshot from 2023-01-31 23-16-58](https://user-images.githubusercontent.com/37107350/215905677-cf43a071-9001-4532-b736-7bbbc8fa0914.png)

The logs at `logs/prod/prod.log` show the following:
```
[2023-01-31 23:16:55] request.INFO: Matched route "saml_acs". {"route":"saml_acs","route_parameters":{"_route":"saml_acs","_controller":"Hslavich\\OneloginSamlBundle\\Controller\\SamlController::assertionConsumerServiceAction"},"request_uri":"https://crm-test.ubiwhere.com/saml/acs","method":"POST"} []
[2023-01-31 23:16:55] php.INFO: Deprecated: Return type of SugarDateTime::createFromFormat($format, $time, $timezone = null) should either be compatible with DateTime::createFromFormat(string $format, string $datetime, ?DateTimeZone $timezone = null): DateTime|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice {"exception":"[object] (ErrorException(code: 0): Deprecated: Return type of SugarDateTime::createFromFormat($format, $time, $timezone = null) should either be compatible with DateTime::createFromFormat(string $format, string $datetime, ?DateTimeZone $timezone = null): DateTime|false, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /bitnami/suitecrm/public/legacy/include/SugarDateTime.php:111)"} []
[2023-01-31 23:16:55] php.INFO: Deprecated: str_ireplace(): Passing null to parameter #1 ($search) of type array|string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: str_ireplace(): Passing null to parameter #1 ($search) of type array|string is deprecated at /bitnami/suitecrm/public/legacy/include/utils/db_utils.php:135)"} []
[2023-01-31 23:16:55] php.INFO: Deprecated: str_ireplace(): Passing null to parameter #2 ($replace) of type array|string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: str_ireplace(): Passing null to parameter #2 ($replace) of type array|string is deprecated at /bitnami/suitecrm/public/legacy/include/utils/db_utils.php:135)"} []
[2023-01-31 23:16:55] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2023-01-31 23:16:55] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\Saml\\AppSamlAuthenticator"} []
[2023-01-31 23:16:55] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Hslavich\\OneloginSamlBundle\\Security\\Http\\Authenticator\\SamlAuthenticator"} []
[2023-01-31 23:16:55] php.INFO: Deprecated: Function libxml_disable_entity_loader() is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Function libxml_disable_entity_loader() is deprecated at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Utils.php:85)"} []
[2023-01-31 23:16:55] php.INFO: Deprecated: Function libxml_disable_entity_loader() is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Function libxml_disable_entity_loader() is deprecated at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Utils.php:89)"} []
[2023-01-31 23:16:55] php.INFO: Deprecated: Function libxml_disable_entity_loader() is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Function libxml_disable_entity_loader() is deprecated at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Utils.php:144)"} []
[2023-01-31 23:16:55] php.INFO: Deprecated: Function libxml_disable_entity_loader() is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Function libxml_disable_entity_loader() is deprecated at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Utils.php:146)"} []
[2023-01-31 23:16:55] request.CRITICAL: Uncaught PHP Exception OneLogin\Saml2\ValidationError: "Found an Attribute element with duplicated Name" at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Response.php line 822 {"exception":"[object] (OneLogin\\Saml2\\ValidationError(code: 41): Found an Attribute element with duplicated Name at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Response.php:822)"} []
```

Do I have something wrong with the mapping in `extensions/custom/config/services/saml/saml.yaml`?
```
parameters:
  saml.autocreate.attributes_map:
    email: email
    'urn:oid:2.5.4.4': last_name
    'urn:oid:2.5.4.42': first_name
```

I've tried looking for the SAML values in `logs/auth.log` but the file does not exist. I am somewhat blind without this to debug.

**Comment by TimmiORG** [comment]
Hi @simao-silva 

you would need to check the response from keycloak now.
Please check inside the client, client-scope,<name-dedicated if you have disable full scope on the scope tab.

I don't use autocreate in SuiteCRM. So in the same clientscope you would need to configure the mapper for the data you want to transmit. From the screen shot it looks like you are using the email as userid. So this would be something you would need to map on the SuiteCRM side.

Maybe you create first a user inside SuiteCRM and just try to authenticate against this as you only need to manage to provide the correct username for this before messing with the mapping.

The auth.log was also for me only visible after a while of on success or so. The production log is providing good information. 
It will tell you mapping issues like don't find uid or something like that. Your current issue is the following:

`[2023-01-31 23:16:55] request.CRITICAL: Uncaught PHP Exception OneLogin\Saml2\ValidationError: "Found an Attribute element with duplicated Name" at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Response.php line 822 {"exception":"[object] (OneLogin\\Saml2\\ValidationError(code: 41): Found an Attribute element with duplicated Name at /bitnami/suitecrm/vendor/onelogin/php-saml/src/Saml2/Response.php:822)"} []`

This I guess will be solved with deactivation of full scope.

**Comment by simao-silva** [comment]
Hi @TimmiORG,
Disabling `Full scope allowed` and adding the predefined mappers `X500 email`, `X500 givenName` and `X500 surname`  did the trick and now I am able to go to SuiteCRM, redirected to Keycloak and come back and see the dashboard, even with a user that did not previously existed in SuiteCRM. 
For the key signing, I have to enable `Sign assertions`, `Client signature required` and `Encrypt assertions`, and import the files that I set in the variables `SAML_SP_PRIVATE_KEY` and `SAML_SP_CERT_FILE` or I am doing it wrong?

**Comment by TimmiORG** [comment]
Hi @simao-silva 
sounds good already.
I do not have Encrypt assertions enabled. So I can't comment on that one.
So not sure if this is causing issues but I did not do anything else than that.

**Comment by simao-silva** [comment]
Hi @TimmiORG,
 Thank you for your support and patience. I will explore that in the mean time.

**Comment by shakeelahmedRT** [comment]
@simao-silva Where did you get "# IDP certificate"?

**Comment by simao-silva** [comment]
@shakeelahmedRT if you are using Keycloak go to `Realm settings` -> `Keys` -> `RS256` and click on the `Public key` button.

**Comment by g-nardiello** [comment]
I'm doing the same procedure. It works but fails on logout redirect.

This is my flow, to better explain:
1. Go to suitecrm home page [OK]
2. Redirected to keycloak login [OK]
3. Login into keycloak [OK]
4. Redirected to suitecrm home [OK]
5. Logout from suitecrm [Partially working]

It redirects to keycloak page and stops here with the message "We are sorry... Logout failed".
On keycloak logs:
`ERROR [org.keycloak.protocol.saml.SamlProtocol] (executor-thread-566) Can't finish SAML logout as there is no logout binding set.  Please configure the logout service url in the admin console for your client applications.`

If I return to suitecrm it is successfully logged out and could login again.

I don't understand that message. Could anyone help me? Thanks

**Comment by simao-silva** [comment]
@g-nardiello try start Keycloak with `--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true`

**Comment by gil0109** [comment]
Using: Bitnami Docker image of SUITECRM Version 8.5.1
PHP Version: 8.1.27

setup as per above and confirmed against @TimmiORG 

No redirection occurring to keycloak server on login.

I see this in the log:

[08-Feb-2024 06:29:08 UTC] PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 134
[08-Feb-2024 06:29:08 UTC] PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php on line 144
[08-Feb-2024 06:29:08 UTC] PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\Session\Session::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Session.php on line 131
[08-Feb-2024 06:29:08 UTC] PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\Session\Session::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /bitnami/suitecrm/vendor/symfony/http-foundation/Session/Session.php on line 141

No issues logging in with regular login.

I confirmed the system is looking at the extensions/custom/config/packages/hslavich_onelogin_saml.yaml as it errors out when i had an error in the file.

Any help would be appreciated..
Happy to provide my config if you feel the above errors have nothing to do with the issue.

**Comment by gil0109** [comment]
Within the docker container I had to use this command instead 
rm -r /bitnami/suitecrm/cacke

which made no difference.

**Comment by gil0109** [comment]
i think the bitnami suitecrm docker image doesn't work with saml..

**Comment by simao-silva** [comment]
> i think the bitnami suitecrm docker image doesn't work with saml..

The image that I was working with when I opened the PR was `docker.io/bitnami/suitecrm:8.3.0` and I was able to get it to work with Keycloak.
