### ISSUE TITLE
Notifications (Alert module) widget doesn't updated.

### ISSUE THREAD

**Issue by lmax85** [salesagility/SuiteCRM-Core#19]
#### Issue

Notifications (Alert module) widget doesn't updated.
#### Expected Behavior

When new alerts inserted in database widget must update.
#### Actual Behavior

Notification widget is just static example
#### Possible Fix

Need to implement right behavior in angular?))
#### Steps to Reproduce

1. Open 2 windows with different logged in users
2. Window 1 - open Any Lead Entity and assign it to user 2
3. Wait a 1 minute before javascript call endpoint for new notifications
4. Check in developer tools for endpoint `/legacy/index.php?module=Alerts&action=get&to_pdf=1`
5. Here must be new notification... But notification widget still same...

#### Context

Hi everyone! As i understood from code - for now Notifications (Alert module) is static template in beta versions… Is it right? or maybe it is possible to change it for working with notifications like in v7 (https://community.suitecrm.com/t/how-to-create-notifications-by-using-workflows-logic-hooks/70809)?

![Screenshot 2021-09-22 at 14 06 54](https://user-images.githubusercontent.com/7403047/136508380-cb718a68-9104-482e-9cee-87ab557a01c2.png)
![Screenshot 2021-09-22 at 14 15 18](https://user-images.githubusercontent.com/7403047/136508790-b451a730-5aa4-4dcd-bb05-3155fd07d521.png)

Maybe it will resolve in release?

thank you for your time:)

#### Your Environment

* SuiteCRM Version used: ver. 8-Beta-2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 94.0.4606.81 (Official Build) (arm64)
* Environment name and version (e.g. MySQL, PHP 7): 10.2.39-MariaDB-1:10.2.39+maria~bionic, PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by johnM2401** [comment]
Hey there @lmax85 

Just to keep you in the loop, the Notification/Alert functionality was not implemented for the initial release of SuiteCRM 8

However, I've marked this as an "Enhancement", as this would be good to add in the future.

Thank you for raising this!
