### ISSUE TITLE
PHP Parse Error Line 1150 in Imap2Handler.php

### ISSUE THREAD

**Issue by jimroh** [salesagility/SuiteCRM-Core#204]
S8 v 8.2.2 on CentOS. There is a comma after the second (last) parameter of the $this->search(param, param) method call (IE $this->search($param, $param,) which causes a PHP Parse Error. This, in turn, can cause the Administration screen to not render correctly.

The coder obviously treated this portion of code as an array rather than a list of method parameters.

Removing the comma after the last parameter fixes this issue.

**Comment by lukio** [comment]
Hi @jimroh the legacy code, should be fixed at [SuiteCRM](https://github.com/salesagility/SuiteCRM) repository. 

We could filled a ticket over there a create a PR to fix it.

**Comment by lukio** [comment]
Hi @jimroh which version of PHP you are using it? It seems that trailling comma is accepeted since PHP 7.3.x

More information:

- https://wiki.php.net/rfc/trailing-comma-function-calls
- https://laravel-news.com/php-trailing-commas-functions

Cheers!

**Comment by jimroh** [comment]
OK. Thanks. I'm using 7.2.x. I will upgrade my PHP version.
