### ISSUE TITLE
User-created field not appearing in layout

### ISSUE THREAD

**Issue by romleinster** [salesagility/SuiteCRM-Core#208]
I created a field (called volume) using Studio in the Products module:
![field](https://user-images.githubusercontent.com/8878992/216119457-e533dfd2-1bf2-4da6-837c-448bf6d34813.png)
Now I want to use that field in my "New Product" layout. I modify each layout (edit, detail and quick create) to use my new field as follows:
![layout](https://user-images.githubusercontent.com/8878992/216118042-23f14475-c982-4022-acdd-c391f7073af3.png)
but my create page doesn't apply the changes to the layout:
![create](https://user-images.githubusercontent.com/8878992/216118259-a06bf533-a586-453d-80a0-8c82c7ec4e88.png)

in deprecations.log I see several lines like:
`[2023-02-01 17:10:42] php.INFO: Deprecated: Creation of dynamic property AOS_Products::$volume_c is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Creation of dynamic property AOS_Products::$volume_c is deprecated at /srv/http/suitecrm8-2-3/public/legacy/data/SugarBean.php:590)"} []`

I'm running
suitecrm 8.2.3
apache 2.4.55
php 8.2.1
mariadb 10.9.4
archlinux / 6.1.7-arch1

client browser 
Firefox 109.0.1

**Comment by pgorod** [comment]
You're using an unsupported PHP version

https://docs.suitecrm.com/8.x/admin/compatibility-matrix/
