### ISSUE TITLE
WebToPerson form fails with 500 error in SuiteCRM 8.2.3

### ISSUE THREAD

**Issue by rtcare** [salesagility/SuiteCRM-Core#209]
#### Issue
After upgrading from 7.13 to 8.2.3, the Web to Person lead capture forms no longer work when using PHP 8.

#### Expected Behavior
Web to Person forms created through the wizard should create leads.

#### Actual Behavior
Instead, the server returns a 500 error. I have set the environment to qa in the .env file, and was able to obtain the following trace:

```
TypeError:
array_key_exists(): Argument #2 ($array) must be of type array, Lead given

  at /home/user/apps/suitecrm/public/legacy/modules/Campaigns/WebToPersonCapture.php:141
  at require_once()
     (/home/user/apps/suitecrm/public/legacy/include/MVC/Controller/SugarController.php:1010)
  at SugarController->handleEntryPoint()
     (/home/user/apps/suitecrm/public/legacy/include/MVC/Controller/SugarController.php:465)
  at SugarController->process()
     (/home/user/apps/suitecrm/public/legacy/include/MVC/Controller/SugarController.php:361)
  at SugarController->execute()
     (/home/user/apps/suitecrm/public/legacy/include/MVC/SugarApplication.php:101)
  at SugarApplication->execute()
     (/home/user/apps/suitecrm/public/legacy/index.php:52)
  at require('/home/user/apps/suitecrm/public/legacy/index.php')
     (/home/user/apps/suitecrm/public/index.php:54)                
```

I have tried the above using PHP 8.0. 

#### Steps to Reproduce
1. Create a form using the Web to Person wizard, using firstname, lastname, and phone fields
2. Fill in the fields as required
3. Submit the form

#### Context
**Downgrading to PHP 7.4 solves the issue.** However, it is out of security support, so it is not the ideal solution.

#### Your Environment

* SuiteCRM Version used: 8.2.3
* Browser name and version: Chrome Version 109.0.5414.120 (Official Build) (64-bit)
* Environment name and version: MariaDB, PHP 8.0, 8.1
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by pgorod** [comment]
https://community.suitecrm.com/t/suitecrm-7-12-9-php8-0-webtopersoncapture-not-working/87841/4

**Comment by rtcare** [comment]
Can confirm that downgrading PHP to 7.4 solves the issue, although, as the link above mentions, 7.4 is out of active security support so maybe not the best solution. 

I have updated my original issue report which was incorrectly stating that this issue occurs with 7.4 as well. It only occurs with PHP 8. 

The answer above by @abuzarfaris also mentions the following code fix:

>  fix the line 146 by changing
```
array_key_exists($person) 
```
> to
```
property_exists($person)
```

Seems straightforward to implement but it's not update-friendly. I can create a PR here if welcome.
