### ISSUE TITLE
Blank page when trying to add a new product

### ISSUE THREAD

**Issue by bralandealmeida** [salesagility/SuiteCRM-Core#211]
#### Issue
I did a fresh install of SuiteCRM on version 8.2.3 and when trying to create a new product in the dashboard, SuiteCRM returns a blank page.

When analyzing the logs, I noticed a FATAL Error referring to a validation of the product image extension. It turns out that I didn't send any images, so I suppose this validation shouldn't exist.

#### Expected Behavior
Product added successfully.

#### Actual Behavior
Blank page.

#### Possible Fix
I believe the following lines should be inside an if block to validate the existence of a file upload.

https://github.com/salesagility/SuiteCRM-Core/blob/hotfix/public/legacy/modules/AOS_Products/AOS_Products.php#L67-L71

**Comment by clemente-raposo** [comment]
The fix was applied in Suite 7 and ported over to Suite 8. 
Closing this issue.

Thank you for the contributions.
