### ISSUE TITLE
New created users cannot login (invalid credentials)

### ISSUE THREAD

**Issue by kale1d0code** [salesagility/SuiteCRM-Core#213]
#### Issue

Any user created by another user (any other than the default user) cannot login. message states invalid credentials, despite a copy and paste of password.

#### Expected Behavior

CRM to navigate to home page after entering credentials

#### Actual Behavior

"Login credentials incorrect, please try again." displays in a popup message. devtools has the following console messages
Failed to load resource: the server responded with a status of 401 ()
Login failed
(nothing is printed in suitecrm.log)

#### Steps to Reproduce

1. Setup SuiteCRM 8.2.3
2. create users
3. attempt to login as users
4.

#### Context

Web Application is unusuable

#### Your Environment

* SuiteCRM Version used: 8.2.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 110
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.0.26 MariaDB 10.9.4
* Operating System and version (e.g Ubuntu 16.04): Alpine 3.16.3

**Comment by IgorA100** [comment]
Yes, there is such a problem. Doesn't appear regularly.
It's probably related to this: https://github.com/salesagility/SuiteCRM-Core/issues/180

**Comment by kale1d0code** [comment]
Hi, Igor
Thanks I am aware of the CSRF token problem, I believe this maybe a separate issue however.
I only had a CSRF issue when upgrading from 7.x

When modifying a users password, devtools prints this error message
```
Failed to launch 'location:%20index.php?action=EditView&module=Users&record=' because the scheme does not have a registered handler.
```
the user_hash is also set to NULL in the database.
When setting a user_hash from sql I am able to login

**Comment by kale1d0code** [comment]
Hi I have found the problem.

It was to do with my reverse proxy and not the CRM system.
Closing now
