### ISSUE TITLE
Version 8.2.3 Dashlets "My Open Tasks" spoils the design

### ISSUE THREAD

**Issue by IgorA100** [salesagility/SuiteCRM-Core#214]
#### Issue

Dashlets "My Open Tasks" spoils the design

#### Expected Behavior

The design must not be damaged!

#### Actual Behavior

Seen in the screenshot:
![SuiteCRMTasksBUG](https://user-images.githubusercontent.com/5006170/218559959-e52e4a79-267c-4d8b-9869-3f1ab64e983f.png)

#### Steps to Reproduce

1. Go to https://suite8demo.suiteondemand.com/ and add the Dashlet "My Open Tasks" to your home screen.
2. The problem occurs only when one or more tasks displayed in the Dashlet do not have the "Parent Type" parameter set. If this "Parent Type" option is selected, then there is no problem!

#### Context

This is HORRIBLE, I have a lot of words :( A release has been released with such a problem .....
This needs to be fixed IMMEDIATELY!!!

#### Your Environment

* SuiteCRM Version used: 8.2.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 110.0.5481.78 (64 бит)
* Environment name and version (e.g. MySQL, PHP 7): DEMO SITE !!! & PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): DEMO SITE !!! & Ubuntu Server 22.04

**Comment by IgorA100** [comment]
Really nobody sees such huge problem???

To access the demo, please use the following details:
Username: will
Password: will

**Comment by pgorod** [comment]
I see it, I just don't know how to fix it. It would take some time and effort, and I can't invest that effort right now.

I understand it is frustrating, but please bear in mind that there is a limit to what can be done based solely on good will and free labor. If you are in critical trouble with this bug, you should consider paying someone to fix it for you.

**Comment by IgorA100** [comment]
> I see it

Oh dear friend, thanks for your reply!
Don't think I'm rushing anyone. I perfectly understand everything!
I have no complaints about the speed of fixing the problem.
I just thought this issue was NOT confirmed and not planned to be fixed.
Thank you!
