### ISSUE TITLE
Dropdown fields marked as required do no trigger validation unless the value is changed

### ISSUE THREAD

**Issue by eojedapilchik** [salesagility/SuiteCRM-Core#219]
#### Issue
In Edit and Create View if you have dropdown fields marked as required, they are not validated once the view is submitted unless you change the value of the record previously if it is empty and you never modify the value it will not trigger the validation error

#### Expected Behavior
Once a dropdown field is marked as required it should throw the field validation error if the value is empty, on submit

#### Actual Behavior
The dropdown field with an empty value and set as required is not triggering the validation error on submit. For example you could submit an opportunity without a sales stage

#### Steps to Reproduce

1. Go to the Opportunity module.
2. Create a new opportunity.
3. Add values for all required fields but leave the sales stage empty.
4. Save the opportunity.
You can replicate this with any module that has dropdowns as required fields.

![image](https://user-images.githubusercontent.com/53310216/220317880-be2f53a9-d2d0-455f-87b2-1af7bd1d5f92.png)
![image](https://user-images.githubusercontent.com/53310216/220318000-255216ee-ed3f-479f-b89d-53b67480e454.png)

#### Your Environment

* SuiteCRM Version used: 8.2.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04

**Comment by 4Hasham** [comment]
Same with the relate fields, no validation occurs unless value is changed.

This occurs in Cases module too, seems it's a problem throughout the CRM in modules that use the SuiteCRM 8 UI in record-view.
