### ISSUE TITLE
Invalid CSRF Token when running native authentication with SAML configured

### ISSUE THREAD

**Issue by sweettbug3** [salesagility/SuiteCRM-Core#230]
#180 was only partially fixed
 
The fix with the 8.2.3 update works for me in part.

My SuiteCRM instance is configured with keycloak authentication (SAML) but as described in the documentation, native authentication can be accessed via the url `https://<your-suitecrm-instance>/auth`.
When I try to access this address I get a blank page with the error with the Invalid CSRF token

Hopefully this can help you to reproduce it

_Originally posted by @Quent1L in https://github.com/salesagility/SuiteCRM-Core/issues/180#issuecomment-1412189846_

This is also an issue for 8.2.4

**Comment by Quent1L** [comment]
Hi, do you have any news about this bug?

**Comment by sweettbug3** [comment]
I have still not been able to get native login to work at the same time as saml login is configured.  

But I have had success logging into saml without CSRF errors, due to patching the core_services.yaml to include an additional path i had added for failed logins. There is some slim chance that there is an additional path that needs to be added there?

**Comment by clemente-raposo** [comment]
Hi @sweettbug3 @Quent1L,

We've been looking into this issue. It should just be a misconfiguration.

While we don't push a fix out, please try adding the following:

On `config/core_services.yaml` add `/auth$` to the following

```
  App\Security\CSRFCookieListener:

    ...

      $routes:
        - path: '(/login$|/$|/auth$|/logout$|/session-status|/auth/logout|/auth/login|/auth/session-status)'
    ...
```

**Comment by sweettbug3** [comment]
I am no longer working on suitecrm, but I am sure the community will appreciate the configuration clarification.Sweettbug3Sent from my iPhoneOn Sep 12, 2023, at 9:53 AM, Clemente Raposo ***@***.***> wrote:﻿
Hi @sweettbug3 @Quent1L,
We've been looking into this issue. It should just be a misconfiguration.
While we don't push a fix out, please try adding the following:
On config/core_services.yaml add /auth$ to the following
  App\Security\CSRFCookieListener:

    ...

      $routes:
        - path: '(/login$|/$|/auth$|/logout$|/session-status|/auth/logout|/auth/login|/auth/session-status)'
    ...
