### ISSUE TITLE
[8.2] multiple files are simply missing in the official "download .zip"

### ISSUE THREAD

**Issue by ghost** [salesagility/SuiteCRM-Core#248]
#### Issue
multiple files are missing from `public/legacy/`
![PrtScr--20230414@135943](https://user-images.githubusercontent.com/59403389/232039100-0d6327d0-f8ef-40b6-ac00-ceaf5d8fdc6b.png)

#### Expected Behavior
all the required files are in official "download .zip"

#### Actual Behavior
```
Fatal error: require_once(): Failed opening required '/var/www/crm/public/legacy/include/../php_version.php' (include_path='/var/www/crm/public/legacy/include/..:.:/usr/share/php') in /var/www/crm/public/legacy/include/utils.php on line 45
```
![Screenshot 2023-04-14 at 14-02-35 An Error Occurred Internal Server Error](https://user-images.githubusercontent.com/59403389/232039071-540fd6ea-2bef-49ca-ad49-a1a3b7658164.png)

#### Possible Fix
include files

#### Steps to Reproduce
1. download official .zip
2. extract and run composer
3. try to use the install page

#### Context
simple install failed on 8.2

#### Your Environment
* SuiteCRM Version used: 8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): any
* Environment name and version (e.g. MySQL, PHP 7): mysql 8, php 7.4
* Operating System and version (e.g Ubuntu 16.04): Debian 11

**Comment by pgorod** [comment]
What are you calling "the official download.zip? Where exactly are you getting it from?

**Comment by dym-sh** [comment]
hm, nevermind, my zip extraction stopped half way for unclear reason
