### ISSUE TITLE
[language] 'Total Cases For This Account' label is too long

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM-Core#25]
The translated text is too long, it may need to be split into 2 lines.

![изображение](https://user-images.githubusercontent.com/5983672/142834453-30a89946-c79c-4d2f-894f-851628236e3d.png)

**Comment by clemente-raposo** [comment]
Hi @likhobory,

Thank you for trying out SuiteCRM 8 and for the feedback.

I'll raise awareness for this internally.

**Comment by likhobory** [comment]
This text has been deleted in 3fb6e4bb8ef435a95da43c2dd6436218a9296816.
