### ISSUE TITLE
ListView: up to 8 columns are displayed

### ISSUE THREAD

**Issue by lukio** [salesagility/SuiteCRM-Core#252]
#### Issue

With suite8 at listview up to 8 columns are displayed. Not mather if I set to display more, the front-end will display only 8 columns.

I set more than 8 columns to be visible at Contacts ListView at demo, but just 8 columns are displayed.

![Captura de pantalla de 2023-04-25 13-49-19](https://user-images.githubusercontent.com/776682/234362441-592013f0-6735-495e-9555-772859500927.png)

![Captura de pantalla de 2023-04-25 13-49-28](https://user-images.githubusercontent.com/776682/234362430-d2418bd6-0679-4eb9-8c3b-1399d2cffc1f.png)

#### Expected Behavior

It should display all the columns that I set to be visible.

#### Actual Behavior

Only the first 8 columns are displayed at listview.

#### Steps to Reproduce

1. Open listview of contacts
2. Click the `columns` link to add more columns to be visible
3. Drag&drop columns to the visible area (more than 8)

*Bug*: when the listview is displayed again only the first 8 fields are displayed.

#### Your Environment

* SuiteCRM Version used: 8.2.4
* Browser name and version: firefox 112.0.1+build1-0ubuntu0.20.04.1

**Comment by scicali** [comment]
same as #174

**Comment by lukio** [comment]
Version 8.3.0 implements the columns that are note being displayed to be visible with a button.

https://docs.suitecrm.com/8.x/admin/releases/8.3/#_hidden_column_display_button

I believe we can close this ticket @clemente-raposo
