### ISSUE TITLE
LDAP Auth does not appear to be working with 8.0

### ISSUE THREAD

**Issue by evilham** [salesagility/SuiteCRM-Core#28]
#### Issue
Hello, I have been checking SuiteCRM with the newest version to see if it can fit our needs, and when trying to debug LDAP authentication (set via the web interface as admin in Password administration) I notice that the code never hits this class:
https://github.com/salesagility/SuiteCRM-Core/blob/master/public/legacy/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php

I tested this by enabling debug logging and adding various logging calls in different places.

It looks to me like the login logic goes through the code in core/backend, which has no single mention of LDAP.

Since it is not mentioned in the release notes, it would be expected that 8.0 is able to perform LDAP authentication.

#### Expected Behavior
LDAP authentication works, or at least is tried, when it is set up.

#### Actual Behavior
LDAP authentication doesn't work.

**Comment by philippmeixner** [comment]
We are experiencing the same issue. Login attempts are met with "internal server error", nothing in suitecrm or php log files. It seems like the LDAP server is never even contacted. The same config is working in our 7.11.19 install.

**Comment by terencejackson8000** [comment]
Same issue with my SuiteCRM 8.0 installation. Is there any update on this?

**Comment by macnewbold** [comment]
Following for updates as well. We're also going through an upgrade and trying to get it working.

**Comment by jeffgoh** [comment]
Same for me - can't upgrade without LDAP auth support

**Comment by craigpanton** [comment]
Hi all,

Thank you for getting in touch regarding LDAP functionality in SuiteCRM 8. This was initially functionality we had planned to include within the initial release phase of SuiteCRM 8, however on investigation it was found that using Symfony configuration for LDAP would be more beneficial than legacy methods. This requires substantial core changes to the existing login and logout processes. 

Subsequently, this feature is currently scheduled to be included within the release of SuiteCRM 8.2. For more information regarding planned releases, please consult the SuiteCRM Roadmap here - https://suitecrm.com/suitecrm-roadmap/ which will be regularly updated.

**Comment by terencejackson8000** [comment]
Thanks @craigpanton. Looks like SAML is taking the same path as LDAP :)

**Comment by francescor** [comment]
Hi, any chance this could be fixed prior to SuiteCRM 8.2 ? 
thanks

**Comment by craigpanton** [comment]
Hi @francescor, it is unlikely that LDAP functionality will be introduced before SuiteCRM 8.2. Please note that our team identify LDAP as a very high priority feature to add, however the significant core changes required for this feature meet a high effort which we estimate to complete in time for the SuiteCRM 8.2 release.

Any changes to this schedule will be included on the Roadmap above.

**Comment by mr2017x** [comment]
@craigpanton is there a workaround e.g by a session provider (also on premise?) maybe also moving away from suite? which alternative could be possible?

or is it possible to “migrate” a “standard” user later on (without hazzle) to a ldap account?

just my thoughts :frowning:

thanks in advance.

**Comment by craigpanton** [comment]
Hi @mr2017x , unfortunately there is not a workaround or alternative at the moment. If LDAP functionality is a requirement for now, we would recommend continuing with SuiteCRM 7 until this has been implemented.

In term of user migration, if this involves LDAP account creation then this would need to be complete manually first.

I hope this helps, but if you have any follow up questions just let me know.

**Comment by mr2017x** [comment]
> uh, I see LDAP is expected to be available in a month https://suitecrm.com/suitecrm-roadmap/
> 
> great!

hope it'll be there then. 8.2 was first announced for at least june ;) but good thing needs time (hopefully)

**Comment by mr2017x** [comment]
> FYI, I just installed a beta of 8.2, and I can't see LDAP feature. Is it expected and not exposed in the UI? Is there a way to configure it in a config file? (not production setup, testing the tool ATM)

check out user configuration or maybe password management under administrative settings.

**Comment by gizahNL** [comment]
What's the progress on this? There haven't been any commits on the develop branch since the release of the first beta. We'd love to start testing this.

**Comment by samiak2011** [comment]
In the roadmap 8.2 scheduled to be released on Aug 2022, now we are on Sep when we will expect the release?

**Comment by mr2017x** [comment]
> In the roadmap 8.2 scheduled to be released on Aug 2022, now we are on Sep when we will expect the release?

actually it was scheduled for april 2022 (afaik) and forwarddated. What issues are ?

**Comment by CaffeineCommander** [comment]
Status update?

**Comment by scicali** [comment]
Solved:
https://docs.suitecrm.com/8.x/admin/configuration/ldap-configuration/

**Comment by olivierlambert** [comment]
Yup, it works well, I'm using it right now :) Next step: OpenID Connect ;)

**Comment by johnM2401** [comment]
Hey Folks

Thank you to all for getting in touch.

Closing this as LDAP has been implemented into SuiteCRM as of 8.2.0

If you still have issues around LDAP, (or encounter any other issues with SuiteCRM), please get in touch!

Thanks!

**Comment by mgalezzo18** [comment]
Hi @johnM2401 
Is the LDAP only working with .env.local modifications? GUI ldap options don't work? I don' t any ldap authentication attempt using GUI
Thanks

**Comment by johnM2401** [comment]
Hey @mgalezzo18 

Yep, That's correct!

The SuiteCRM8 LDAP/SAML functionality is currently configured via the .env.local file

<br>

There *is* a Front-end configuration for LDAP in the CRM, (in Admin->Password Management)
However, this is **only** used in the Legacy v4 API. (Meaning that, to set up LDAP for Suite8, you'd use the .env.local file)
See: https://docs.suitecrm.com/8.x/admin/configuration/ldap-configuration/#_administration_password_management_menu_ldap_configuration

Hopefully this clarifies things!
