### ISSUE TITLE
Basic Search is Redirecting to Localhost In Production/Installed Server

### ISSUE THREAD

**Issue by crossxsecure** [salesagility/SuiteCRM-Core#292]
Hi Team,

I'm recently migrated to SuiteCRM and installed the same in my production server. I'm experiencing an issue where the global search results are not clickable, it is redirecting to localhost URL instead of the production server URL.

I've faced the same issue in v8.0, so I thought of updating the same to v8.3 but it seems to be the same issue there as well. Hence, please advise do we need to have any environment variable that needs to be set up for Basic Search?

#### Steps to Reproduce
1. Search any keyword in Global Search
2. Click on the Search Result
3. Search Result Redirects to Localhost URL Instead it should redirect to Installed Server URL.

#### Your Environment
* SuiteCRM Version used: v8.0 and v8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 
* Operating System and version (e.g Ubuntu 16.04): Docker Image

PFA:

![image](https://github.com/salesagility/SuiteCRM-Core/assets/107629670/eda4adcf-d5de-469d-a595-735eadb949f1)

**Comment by pgorod** [comment]
This is an issue for the Forums (troublehsooting your system) not for Github (reporting confirmed bugs to developers).

https://community.suitecrm.com

Any way, please check your **`site_url`** setting in **`config.php`**. The value you will find there is what you provided when installing.

**Comment by johnM2401** [comment]
Hey @crossxsecure 
Thanks for getting in touch!

As @pgorod noted, this should be configured by the ```site_url``` value in your crm's ```config.php```
(it may also be worth checking the ```RewriteBase``` in your ```.htaccess``` file)

I'll close this issue off for now, but if you are still experiencing this issue after checking your site_url and RewriteBase, please get back in touch.

Thanks again!
