### ISSUE TITLE
Upgrading to 8.3.1 Breaks Installation

### ISSUE THREAD

**Issue by J-Wick4** [salesagility/SuiteCRM-Core#296]
Upgrading from 8.3.0 to 8.3.1 breaks the installation.

**Steps:**

1. Downloaded SuiteCRM-8.3.1.zip 
2. Uploaded to /tmp/package/upgrade
3. Ran the command  './bin/console suitecrm:app:upgrade -t SuiteCRM-8.3.1.zip
4. Reports Success

**Results:**

Page Error 500

Using any CLI command results in the output of:

```
 ./bin/console 
PHP Deprecated:  Return type of Symfony\Component\Security\Core\Exception\AuthenticationException::__wakeup() should either be compatible with Exception::__wakeup(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/domain.net/subdomains/crm/vendor/symfony/security-core/Exception/AuthenticationException.php on line 115

In FileLoader.php line 174:

  The file "../extensions/default" does not exist (in: "/var/www/vhosts/domain.net/subdomains/crm/config") in /var/www/vhosts/domain.net/subdomains/crm/config/core_services.yaml (which is being imported from "/
  var/www/vhosts/domain.net/subdomains/crm/config/services.yaml").


In FileLocator.php line 71:

  The file "../extensions/default" does not exist (in: "/var/www/vhosts/domain.net/subdomains/crm/config").

```

**Environment:**

Rocky Linux 8.8
Apache 2.4 w/ NGINX proxy
Mariadb  10.4.30-MariaDB
Copyright (c) The PHP Group
Zend Engine v4.0.29, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.29, Copyright (c), by Zend Technologies

**Comment by clemente-raposo** [comment]
Hi @J-Wick4,

Thank you for your report.

Did you run `./bin/console suitecrm:app:upgrade-finalize -t SuiteCRM-8.3.1.zip"` after running the `'./bin/console suitecrm:app:upgrade -t SuiteCRM-8.3.1.zip`?

**Comment by clemente-raposo** [comment]
Hi again @J-Wick4,

Anyway, there is a workaround for your issue. Just create a `default` folder under the `extensions`

**Comment by J-Wick4** [comment]
> Hi @J-Wick4,
> 
> Thank you for your report.
> 
> Did you run `./bin/console suitecrm:app:upgrade-finalize -t SuiteCRM-8.3.1.zip"` after running the `'./bin/console suitecrm:app:upgrade -t SuiteCRM-8.3.1.zip`?

Ahh! I didn't see there were new commands for upgrading this version. This fixed my problem; thank you!
