### ISSUE TITLE
"Undefined" record UUID on one-to-one custom module relationship linked field url

### ISSUE THREAD

**Issue by scicali** [salesagility/SuiteCRM-Core#30]
#### Issue
"Undefined" record UUID on one-to-one custom module relationship linked field url

#### Expected Behavior
Get url with record UUID in linked field

#### Actual Behavior
Get "undefined" value in url:
http://localhost/#/test_module1/record/undefined

#### Steps to Reproduce
1. Install as per instructions
2. Create basic custom module in studio
3. Create one-to-one ralationship custom module->account
4. Deploy custom module
5. insert account record
6. insert custom module record
7. link custom module record with account record
8. linked field url have "undefined" record value 

#### Your Environment

* SuiteCRM Version used: SuiteCRM Version used: 8.0.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 94.0.1
* Environment name and version (e.g. MySQL, PHP 7): php 7.3
* Operating System and version (e.g Ubuntu 16.04): debian 10

**Comment by mohamedalmograby** [comment]
any updates about this ?

**Comment by scicali** [comment]
you can temporary enable legacy render for the module, for account module set:

```
    accounts:
      index: false
      list: false
      record: false
```

in config/services/module/module_routing.yaml

then 
repair->rebuild in admin
./bin/console cache:clear from cli

**Comment by vsulak** [comment]
Is it possible to enable render legacy for custom modules?

Is this bug in backend or frontend part?

**Comment by scicali** [comment]
> Is it possible to enable render legacy for custom modules?
> 
> Is this bug in backend or frontend part?

You can try to (temporary) add
`
   <your_module>:
      index: false
      list: false
      record: false
`
in config/services/module/module_routing.yaml

**Comment by vsulak** [comment]
thank you, it works with lowercased name of custom module

**Comment by phil8900** [comment]
I have the same issue and temporary editing the module_routing.yaml didn't fix it for me. The instructions I found here https://community.suitecrm.com/t/custom-module-problem-record-id-undefined/83566/2 didn't change the behaviour either. Any other suggestions?

**Your Environment**
    SuiteCRM Version used: 8.0.3
    Browser name and version: Firefox 97.0 (64-Bit)
    Environment name and version: php 7.3.33
    Operating System and version: Ubuntu 18.04.6 LTS

**Comment by scicali** [comment]
> I have the same issue and temporary editing the module_routing.yaml didn't fix it for me. 
Log in SuiteCRM, open url http(s)://<myurl>/legacy/index.php?module=<module_name>; this is legacy frontend.

If u have the issue, is not this bug; if u haven't, u can't enable legacy frontend editing module_routing.yaml

**Comment by vsulak** [comment]
are there any news for this issue? Is there any way I can help? Can you direct me to either frontend or backend for this? This is quite blocking me since I have extension (detail view action) written for SuiteCRM 8 and legacy view prevents me from using it

**Comment by scicali** [comment]
> are there any news for this issue? Is there any way I can help? Can you direct me to either frontend or backend for this? This is quite blocking me since I have extension (detail view action) written for SuiteCRM 8 and legacy view prevents me from using it

Try this

https://community.suitecrm.com/t/custom-module-problem-record-id-undefined/83566/3

**Comment by Jonyx4** [comment]
> > are there any news for this issue? Is there any way I can help? Can you direct me to either frontend or backend for this? This is quite blocking me since I have extension (detail view action) written for SuiteCRM 8 and legacy view prevents me from using it
> 
> Try this
> 
> https://community.suitecrm.com/t/custom-module-problem-record-id-undefined/83566/3

Only workaround that worked. 

Is there any update about this issue?

**Comment by scicali** [comment]
Confirmed in lastest (8.1)
