### ISSUE TITLE
Problem installing the version 8 of the suitecrm

### ISSUE THREAD

**Issue by Crushoverride007** [salesagility/SuiteCRM-Core#308]
When trying to installing the crm on my server it indexes as below

![CleanShot 2023-08-16 at 21 28 54](https://github.com/salesagility/SuiteCRM-Core/assets/45631812/aa3c82fd-3e75-4ff5-a7b3-32030570cb30)

**Comment by mattlorimer** [comment]
I suggest you look at configuring your webserver in the install guide on the docs, to set it up correctly

https://docs.suitecrm.com/8.x/admin/installation-guide/webserver-setup-guide/#_4_configuring_url_re_writes

but overall for setup issue you would be better asking the in the community form https://community.suitecrm.com/

**Comment by chris001** [comment]
@Crushoverride007 if you have docker, or can install it, you can easily and quickly install the docker image for suitecrm 8, it works.

**Comment by Crushoverride007** [comment]
@chris001 i've found repos on dockerhub do you have the link of the repo for it, please?

**Comment by chris001** [comment]
@Crushoverride007 Sure, it's https://hub.docker.com/r/bitnami/suitecrm/
