### ISSUE TITLE
Status field is dependent on state field but it not responding to changes

### ISSUE THREAD

**Issue by yunusyerli1** [salesagility/SuiteCRM-Core#323]
#### Issue

he status field in the Cases module is showing all values no matter what value is selected in the State field.

#### Expected Behavior

“New” and “In progress” Status drop-down values will be displayed when the State field is set to “Open”.
“Resolved” and “Cancelled” Status field drop-down values will be displayed when the State field is set to “Closed”.

#### Actual Behavior

The status field in the Cases module is showing all values no matter what value is selected in the State field.

#### Possible Fix

checkAndInitAsDynamicEnum() method need to be added to dropdownenum.component. Because the method checks the values depending on a dependant field.

#### Steps to Reproduce

1. In base-field.manifest.ts file change following:
   From :
    'enum.detail': EnumDetailFieldComponent,
    'enum.edit': EnumEditFieldComponent,
   To: 
   'enum.detail': DropdownEnumDetailFieldComponent,
    'enum.edit': DropdownEnumEditFieldComponent,
2. In editview, select State and check Status field. You ll see all values.
3.Select another value in State, and still you will see all the values

#### Context

Status needs to be dynamic dependent on State field. This is a low priority.

#### Your Environment

* SuiteCRM Version used: 8.3.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 115.0.5790.171 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): Wamp Server, PHP 7.4.33, MariaDB 10.4.12
* Operating System and version (e.g Ubuntu 16.04): Windows 11

**Comment by johnM2401** [comment]
Hey Yunus!

I've given this a look and it appears to be Dynamically updating, as expected

See gif:

![caseDyn](https://github.com/salesagility/SuiteCRM-Core/assets/13675281/5a31b2e0-f1d2-45cf-a8c1-5e8b281eec7f)



Is there anything further that is required to replicate this?
(ie: Changing the displayType to dropdown for these fields? or something else?)
