### ISSUE TITLE
RewriteBase populating incorrectly depending on site URL entered in installation config

### ISSUE THREAD

**Issue by TripitakaBC** [salesagility/SuiteCRM-Core#33]
#### Issue
If the user enters an incorrectly formatted URL for the site URL during initial installation configuration, the RewriteBase value populated in /public/legacy/.htaccess file is non-functional. This has the effect of returning an 'Internal Server Error' for all legacy/classic pages but leaves all pages served by the new SuiteCRM8 code to work as expected.

See community forum: https://community.suitecrm.com/t/suitecrm8-install-issues-on-freebsd-truenas/83064

#### Expected Behavior
Without explicit guidance, a user may enter 'localhost' or '<IP address> in the site URL field. Expected behaviors is that the site would accommodate this and work expected, presenting all menus.

#### Actual Behavior
Unless the site URL is formatted correctly, SuiteCRM8 serves legacy/classic page errors as 'Internal Server Error'. SuiteCRM8 'new' code pages (Accounts, Contacts etc) work normally.

#### Possible Fix
Place a user tip explicitly stating the format input required and/or force the input format to be compliant.

#### Steps to Reproduce

1. During install configuration, enter just 'localhost' or any suitable IP address in the site URL field.
2. Complete install config
3. Test 'Administrator' dropdown options for 'Internal Server Errors'
4. View /public/legacy/.htaccess file for the value entered in 'RewriteBase' value. Correct entry should be '/legacy/', not '<whatever was entered in site URL field at config>legacy/'

#### Context
Trying to accomplish setup of SuiteCRM 8.
Without access to legacy pages, the application is non-functional.

#### Your Environment

* SuiteCRM Version used: 8.0.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 94.0.2 and Edge 96.0.1054.34
* Environment name and version (e.g. MySQL, PHP 7): Apache2.4, PHP 7.4, MySQL8
* Operating System and version (e.g Ubuntu 16.04): TrueNAS-12.0-U6.1 (FreeBSD 12) running in iocage jail at patch 12.2-RELEASE

**Comment by braunjulia** [comment]
I faced the same problem, thanks @leibra for the fix. I agree in the UI installer an example would be helpful to know the expected input format.

**Comment by clemente-raposo** [comment]
This issue has been fixed 8.6.0 (see the following commit). Closing

https://github.com/salesagility/SuiteCRM-Core/commit/e9166c941d0b88b5810f1f3a2a043ab932550501
