### ISSUE TITLE
8.4 any create record function

### ISSUE THREAD

**Issue by gib1991** [salesagility/SuiteCRM-Core#340]
Fresh installation 8.4 - a few minor tweaks in studio (added a few fields) 

When i go to create a record for example - Logging a call for a contact within the activities subpanel i am met with the following.

![image](https://github.com/salesagility/SuiteCRM-Core/assets/100914854/600e3054-e34b-4b0f-9eed-19ad860b496a)

Within the logs - It's saying that it's looking for an alias meetings.'date_end' as 'meetings_date_end' from the calls table? The calls table doesn't have any links to the meetings table? And in studio there are no fresh install relationships that would warrant the below query?

Is there anywhere i can oik this out?

Wed Sep  6 11:36:14 2023 [31663][1][FATAL] Mysqli_query failed.
Wed Sep  6 11:36:14 2023 [31663][1][FATAL] SubpanelCustomQueryPort: Error executing custom query Query Failed: SELECT meetings.`date_end` AS `meetings_date_end`  FROM calls  LEFT JOIN calls_cstm ON calls.id$

 AND jt1.deleted=0 INNER JOIN  calls_contacts ON calls.id=calls_contacts.call_id AND calls_contacts.contact_id='722a2b29-ba10-4c6e-4cf8-64f83c5dcda1' AND calls_contacts.deleted=0

  where ((calls.status='Held' OR calls.status='Not Held')) AND calls.deleted=0   ORDER BY `meetings_date_end` DESC LIMIT 1: MySQL error 1054: Unknown column 'meetings.date_end' in 'field list'

https://www.youtube.com/watch?v=HKo0FBXAJOk

suite8.4
debian 10 buster
php 8.2 | tried 8.1
mysql 5.7 (tried v8.0) also

**Comment by johnM2401** [comment]
Hey @gib1991 

Thanks for getting in touch!


hmmmm, I've given this a try on a local copy of 8.4.0 (php82/mariadb10.4), and I seem to be able to create reocrds without issue.

(I've also specifically tried Contacts->Activities Subpanel->Log Call, and this appears to work fine too)

<br>

Do you perhaps know which changes you made in studio?
Was this to any of the affected modules? (ie: Calls/Meetings/Contacts)


Also, do you experience this issue across the entire CRM?
(ie: Cannot create Accounts / Cannot create Leads / etc)

Or just for this relationship?


Thanks!

**Comment by gib1991** [comment]
In the calls section in studio all I've done is remove the mandatory fill requirements on the start/end/duration/direction and subject fields.

I've changed the layout of the call in Display & Edit view to suit

I've added in a field for purely date - as datetime isn't relevant for scenario - and added that into the display and edit views.

![image](https://github.com/salesagility/SuiteCRM-Core/assets/100914854/c3191a3d-1ea8-482e-bc68-231b94ea4497)

What i find interesting is that each method i go to create a call be it a subpanel or through the main navigation bars i'm still getting thrown that unique error and the SQL query below appears in the log at every eventuality.

I log into the phpmyadmin to try and run that query independant of the system and it's throwing the same error.
![image](https://github.com/salesagility/SuiteCRM-Core/assets/100914854/4f317e9b-2a39-44b9-9c35-d53043d82fc6)

```
SELECT meetings.`date_end` AS `meetings_date_end`  FROM calls   LEFT JOIN  users jt1 ON calls.a$

 AND jt1.deleted=0 INNER JOIN  calls_contacts ON calls.id=calls_contacts.call_id AND calls_contacts.contact_id='722a2b29-ba10-4c6e-4cf8-64f83c5dcda1' AND calls_contacts.deleted=0

  where ((calls.status='Held' OR calls.status='Not Held')) AND calls.deleted=0   ORDER BY `meetings_date_end` DESC LIMIT 1
```

When i use reset module to calls to bring it back to default - I'm still met with the same error, I don't understand why the calls is trying to alias "MEETINGS" table when there isn't a default relationship between those two on a fresh install? And there isn't a join on the query to bring the meetings. table into the relation (does that make sense?)

I can provide you with access to my install if you'd like to take a nosy - I'm trying to eliminate all the snags before putting too much effort into production.

May be helpful to also note that the record does create - but it always throws up the "Error occured while fetching records"

I've experienced a few relationship issues with a few of the other modules and a few that i've created from new (basic fields) - using the nav bar on subpanel to create the record it's not linking them to the parent (i.e. Studio > Module Builder > Basic > Many to Many relationship > FoodBank to Contacts 

Load up the contact, expand the foodbank subpanel, click add record - input details & save, screen refreshes but there's no record on the parent record - have to manually link them.

**Comment by johnM2401** [comment]
Hey!

Thank you for getting in touch with further info!

hmmm, I've noticed that the field list in your ```Studio->Calls->Fields``` screenshot doesn't list any custom fields, whereas your Youtube video does. (ie: Next Call Date / Flag Reason / etc)

Typically, when custom fields are created via studio, they show with an asterisk.
ie:
![image](https://github.com/salesagility/SuiteCRM-Core/assets/13675281/1ca3ec13-fa48-4e56-82f2-166f97381f66)

<br>

Have you perhaps added any fields/custom changes to these modules directly via the codebase?
(ie: through /extensions/ or /custom/ directories?   Or via the detailview metadata? or elsewhere? )

If so, this may also explain the "Error occured while fetching records" error showing on page-load, and would be a good place to investigate further.


<br>

Thanks!

**Comment by gib1991** [comment]
I figured out why i'm getting these responses and i've remedied at this end.
In the activities/history sub panels i commented out a few lines on the subpaneldefs within each respective module and it's working as intended :)
