### ISSUE TITLE
 Sutecrm 8.4.0 validation on empty date fields

### ISSUE THREAD

**Issue by sasotech** [salesagility/SuiteCRM-Core#347]
#### Issue
When having multiple date fields in Account, we need some of them to stay empty. When saving i get “There are validation errors” message. Because of validation, we cannot save when editing the Account.

#### Expected Behavior
There should be no validation error message on empty date fields.

#### Actual Behavior
When saving empty date field i get “There are validation errors” message.

#### Possible Fix
Remove validation for empty date fields, when saving.

#### Steps to Reproduce
It was recognized by John as bug here:
https://community.suitecrm.com/t/sutecrm-8-4-empty-date-fields/90267/3

#### Context
This is a high priority bug for us.

#### Your Environment

* SuiteCRM Version used: 8.4.0
* Browser name and version Chrome 116.0.5845.179 (Uradna različica) (arm64), Safari, Firefox
* Environment name and version PHP 8.2. 
* Operating System and version Cpanel

**Comment by TwizzX17** [comment]
This issue should be solved by the  [pull request](https://github.com/salesagility/SuiteCRM-Core/pull/351) i created a couple of days ago. The issue is caused by the field is getting an empty string, which is not a valid date. The intended default value is NULL.
