### ISSUE TITLE
Module builder errors

### ISSUE THREAD

**Issue by vsulak** [salesagility/SuiteCRM-Core#35]
#### Issue

After fresh installation of Suite CRM 8.0.0, Module builder opens modal window with error message and other errors are in browser console.

<img width="523" alt="Screenshot 2021-12-02 at 10 35 08" src="https://user-images.githubusercontent.com/6022594/144395818-a2613ad2-6d0b-4d31-b804-b241def39a00.png">

Rendered error:
```
Warning: Creating default object from empty value in /var/www/html/public/legacy/modules/ModuleBuilder/views/view.modulefields.php on line 109
```

Console errors:
```
Failed to load resource: the server responded with a status of 404 (): /legacy/modules/Administration/Search/ajaxSubmit.js
```
File `ajaxSubmit.js` not in production package after installation. Only reference to this file is found in `public/legacy/modules/Administration/Search/ElasticSearch/view.tpl:154`
```
Failed to load resource: the server responded with a status of 404 (): /%22themes//suite8//images//icon_home.png?v=0kE0lI62WZjkj_geRkWwbQ\%22
```
File in `public/legacy/themes/suite8/images/icon_home.png`
```
Failed to load resource: the server responded with a status of 404 (): /%22themes//default//images//icon_back.gif?v=0kE0lI62WZjkj_geRkWwbQ\%22
```
File in `public/legacy/themes/default/images/icon_back.gif`
```
Uncaught SyntaxError: Invalid or unexpected token: VM773 index.php
Uncaught SyntaxError: Invalid or unexpected token: index.php?type=studio&module=ModuleBuilder&action=index
```

#### Expected Behavior

Use module builder

#### Actual Behavior

Module builder not usable - modal window with 

#### Steps to Reproduce

1. Clean install with demo data
2. Open Module builder `/#/module-builder/index?type=studio`
3. Expand single Module, e.g. Contacts
4. Click "Fields" (modal with error appears)
5. Click "Add field" or "Edit labels" ("Invalid or unexpected token" errors appear in console)

#### Your Environment

* SuiteCRM Version used: 8.0.0 prod release
* Environment: PHP 7.4, MariaDB 10.6
* OS: Docker Alpine 3.14.2
* Browser: Chrome 96.0.4664.55

**Comment by clemente-raposo** [comment]
Hi @vsulak,

Thank you for trying out SuiteCRM 8 and for your feedback.

### Possible fix 
Do you have `display_errors` active on `php.ini`? Could you try setting it to the following please?

`display_errors = Off`

### Another thing to look into 
Another thing to check on `php.ini` is `error_reporting`. Could you please check if its properly set?

The following section of the SuiteCRM 8 install guide may help:
[SuiteCRM 8 Install guide - 1.4 Configure php error_reporting](https://docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing/#_1_4_configure_php_error_reporting)

**Comment by vsulak** [comment]
i turned display_errors off and it seems to work now. Thank you

**Comment by clemente-raposo** [comment]
Hi @vsulak,

Glad to hear. Closing the issue.
