### ISSUE TITLE
Undefined Labels in Workflow Manager

### ISSUE THREAD

**Issue by J-Wick4** [salesagility/SuiteCRM-Core#353]
Version 8.4.0

A bunch of labels are undefined.

![Screenshot 2023-09-30 at 12 28 55 AM](https://github.com/salesagility/SuiteCRM-Core/assets/1954540/6d86317c-87a0-414e-97fa-6a10a1b26ab8)

**Comment by pgorod** [comment]
This is very typical of server setup problems, I don't think it's a bug.

If you don't see the same problem on the live demo, I would suggest asking about this in the forums.

**Comment by J-Wick4** [comment]
I was able to correct this, which was a permission issue. 

https://docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing/
