### ISSUE TITLE
How to connect via the GraphQL Api?

### ISSUE THREAD

**Issue by bch80** [salesagility/SuiteCRM-Core#354]
#### Issue

What is the endpoint to connect via the GraphQL API?
How to connect? (Documentation is lacking)

#### Your Environment

* SuiteCRM Version used: 8.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium
* Environment name and version (e.g. MySQL, PHP 7): 8.1, MariaDB
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04

**Comment by mattlorimer** [comment]
Question more suited to [community forum](https://community.suitecrm.com/)
