### ISSUE TITLE
Opportunity list view - columns not updating

### ISSUE THREAD

**Issue by TwizzX17** [salesagility/SuiteCRM-Core#355]
#### Issue

I've encountered an issue regarding the list view, when browsing opportunities. It seems like certain columns are only updating sometimes, on pagination. Specifically  i see this issue on the column "sales_Stage". The only thing i can see that should be unique to this column (compared to the others), is that it is based on the EnumDetailFieldComponent. I cannot exclude that any other field type are having issues as well.

When debugging the code, it seems like it is creating a field with the correct value, on running the "getField" method in table-body.component.ts. When jumping to the dynamic-field.component.ts, i can see on the trigger of "ngOnChanges", that the "field" key is inside the changes parameter and is containing the correct value. 

To my limited angular knowledge, i would expect the field to be updated, but i seems not to be.
The fact that is it only some of the records, on the column sales stage that is not updating, makes this bug hard to identify.
But it seems like it is always the same records on the tables that are having issues, which can help us narrow down the problem.

#### Expected Behavior

All records on the list should display values that are a part of the record information.

#### Actual Behavior

When the application is rendering each column for each record, the column of SaleStaging is sometimes not updating the value.

#### Possible Fix

The focus should most likely be on the functionality of onChange, with the angular application.

#### Steps to Reproduce

1. Enter some dummy data into your application, to be able to paginate. (I've about 700 opportunities)
2. On changing the page, where each column are updated, the you should be able to identify specific fields are containing the old value.

#### Context

I'm not able to rely on the information that i see, which i find crucial, when browsing the application.

#### Your Environment

* SuiteCRM Version used: 8.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Google Chrome Version 117.0.5938.92 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): php 8.2
* Operating System and version (e.g Ubuntu 16.04): ubuntu 20

**Comment by johnM2401** [comment]
Hey folks!

I believe you may be right @scicali, this looks to be the same issue.

I'll mark this ticket as a duplicate for now, unless you disagree @TwizzX17 ?

<br>

In the meantime, there is a very recent PR that *should* resolve these issues: https://github.com/salesagility/SuiteCRM-Core/pull/356

It may be worth giving this change a try to see if it resolves your issues?
(as always, its worth making a backup before making any code changes)

Thanks !

**Comment by TwizzX17** [comment]
Hi @scicali and @johnM2401,
I think you guys are right, this is a duplicate ticket.

I've tested the PR #356 and it looks like it is fixing the issue in my local development environment.
I think i will try and run it to production, to create a temporary fix, until it is fixed in the official release.

Should I close this ticket?

Thanks a lot!

**Comment by johnM2401** [comment]
Hey @TwizzX17 

Ah great!
I'm glad to hear that resolved your issue.

I'll close this ticket off, but keep the other one open for now. (as the PR isn't yet merged into the project)

Thanks for confirming and getting in touch!
