### ISSUE TITLE
Radio fields show up as textfields

### ISSUE THREAD

**Issue by jobrien2001** [salesagility/SuiteCRM-Core#358]
#### Issue
Radio fields show up as textfields

#### Expected Behavior
Radio fields should be radio fields

#### Actual Behavior
Radio fields show up as textfields when creating a record or editing

#### Steps to Reproduce

1.  Make a radio field in studio
2.  Add field to edit layout
3.  Create/edit a record and watch the radio field you created show up as type "text"

#### Your Environment

* SuiteCRM Version used: 8.40
* Browser name and version (Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10 PHP 8
* Operating System and version (e.g Ubuntu 16.04): WAMP

**Comment by BastianHammer** [comment]
I can confirm this, still in 8.5:

![image](https://github.com/salesagility/SuiteCRM-Core/assets/96183835/f3dca509-0bee-4307-97e0-e2586b4860ff)
![image](https://github.com/salesagility/SuiteCRM-Core/assets/96183835/02d6e0e7-ed20-435f-af9b-ab9e52876569)
