### ISSUE TITLE
Cannot input negative in Longitude and Latitude field

### ISSUE THREAD

**Issue by tranhoangbao** [salesagility/SuiteCRM-Core#364]
#### Issue

Cannot input negative value in LONG and LAT
#### Expected Behavior

Input negative value in LONG and LAT, and then cannot save record
#### Actual Behavior

System alert: Invalid float format. Expected: '1,000.5' 
#### Steps to Reproduce

1. add long and lat field to Account
2. input negative value
3. system prevent save with red alert below these field: Invalid float format. Expected: '1,000.5' 
4.

#### Your Environment

* SuiteCRM Version used: 8.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 118
* Environment name and version (e.g. MySQL, PHP 7): mysql, php 7.4
* Operating System and version (e.g Ubuntu 1.04): Ubuntu 20

**Comment by johnM2401** [comment]
Hey!

Thank you for raising this issue.

As of the most recent release, (8.6.0), this issue should now be resolved.

See screenshot:
![image](https://github.com/salesagility/SuiteCRM-Core/assets/13675281/5b3116ec-6d0b-4468-89e7-b7e294771987)


I'm going to close this ticket off for now, but if you are still experiencing issues with these fields then please get back in touch.

Thanks again!
