### ISSUE TITLE
SuiteCRM 8.4.1 - Error Messages When Filtering Date Fields

### ISSUE THREAD

**Issue by aymane59** [salesagility/SuiteCRM-Core#385]
#### Issue
I’m encountering an issue with error messages related to date fields when attempting to **filter** data in certain modules. For example, in the ‘Calls’ module, when I try to apply filters directly, I receive error messages that seem to be related to the ‘Start Date’ and ‘End Date’ fields, which are of datetimecombo type. Strangely, when I click on either of these fields, there is no date format selection available (such as a calendar picker). The same problem appears  also in the demo version of SuiteCRM. Additionally, I’ve attached screenshots that highlight the two error messages displayed.

![MicrosoftTeams-image (3)](https://github.com/salesagility/SuiteCRM-Core/assets/118345952/a5907a51-3eff-45f9-94e2-3cf24149bad3)

#### Expected Behavior
When attempting to use date filters (specifically, ‘Start Date’ and ‘End Date’), I want to have a first dropdown list (with values equals, between..wich is "date_range_search_dom" list) then a second field with a calendar picker which is the default behavior. This is a screenshot of an instance that i found online and where the date filter are used without any errors.

![MicrosoftTeams-image (5)](https://github.com/salesagility/SuiteCRM-Core/assets/118345952/566f6e67-27ee-4c2d-bee5-6d23bc5eee68)

#### Actual Behavior
When attempting to use date filters (specifically, ‘Start Date’ and ‘End Date’), I observe that no options appear upon clicking (neither a calendar nor the ability to manually input a date via the keyboard, not even the first dropdown list "date_range_search_dom" ).

#### Possible Fix
When i delete the DATE type in vardefs for the field 'dateStart' for example, i start seeing the dropdown list when i click on dateStart filter but no more fields (calendar picker).

#### Steps to Reproduce
1. go to calls module
2. click on filter (the errors must show in the console)
3. click on dateStart or dateEnd fields on filter to see if you can choose options to filter or not.

#### Context
Date filtering is a key fonctionnality for my CRM users so they can't achieve many tasks without this filter, especially that the database is quiet big so they can't spend time on searching on listview all the calls or cases, etc.
**I already opened a ticket in suitecrm community (90652/3), the forum team asked me to open an issue here.**
#### Your Environment
* SuiteCRM Version used: 8.4.1
* Environment name and version : php 8.2.7 & mariaDB 10.11.4
* Operating System and version: debian 12
 
 Thank you for your help !

**Comment by Ib-R** [comment]
having the same issue in version 8.4.1

**Comment by massimo-romano** [comment]
same issue in version 8.5.0

**Comment by yuripaoloni** [comment]
I'm also having the same issue

**Comment by MatteoLeonesi** [comment]
same issue.

**Comment by scicali** [comment]
same as #476 ?

**Comment by lukio** [comment]
The funcionality of searching by dates was with version `8.5.1`.

The posibility of searching between was fixed by https://github.com/salesagility/SuiteCRM/pull/10471
