### ISSUE TITLE
Number of days in sales stage < 1 Day

### ISSUE THREAD

**Issue by oguruma1218** [salesagility/SuiteCRM-Core#39]
Maybe not a true "issue" or bug, but I've noticed that when an order has been in the same stage for less than a day, the alert at the top reads "THIS OPPORTUNITY HAS BEEN IN THIS SALES STAGE FOR:  DAY(S)"

It would be much better if it instead read "THIS OPPORTUNITY HAS BEEN IN THIS SALES STAGE FOR: < 1 Day" for orders that have been in the same sales stage for less than a day.

**Comment by Mac-Rae** [comment]
Hi @oguruma1218,

If not an Issue definitely a very valid Suggestion. Have labelled and will pass on internally as this should be a nice easy quality of life change.

Thanks!
