### ISSUE TITLE
Error on Date Component in Filter Mode

### ISSUE THREAD

**Issue by mpuyosa91** [salesagility/SuiteCRM-Core#399]
When you try to use a date field in the filter of any module (i.e. Opportunities), it does not show properly and also does not work.

#### Issue

The date component on filter mode is not working properly, it can not hold a date.

#### Expected Behavior

The date component on filter mode should hold a date to be able to filter by.

#### Actual Behavior

The date component on filter mode is not working properly, it can not hold a date.

#### Steps to Reproduce

1. Open Opportunities in ListView
2. Click the Filter button to open the Filter
3. Check the Expected Close Date field and try to filter by.

#### Context

This is a Medium priority.

#### Your Environment

* SuiteCRM Version used: 8.4.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 119.0.6045.105 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.4.12, PHP 8.2, Node v14.21.3
* Operating System and version (e.g Ubuntu 16.04): Debian 11

**Comment by pgorod** [comment]
Is this the same as #385 ?

**Comment by jtorresj96** [comment]
Hi! I tried the fix, but it only works for default date fields, not for custom fields on custom modules.

**Comment by johnM2401** [comment]
Hey Folks!

Thank you for raising this issue, @mpuyosa91!

This should now be resolved as of the latest release (8.6.0)

See gif, showing some example searches using this field:

![dateFilter](https://github.com/salesagility/SuiteCRM-Core/assets/13675281/1bc9d472-4d78-4520-a89d-f39656e5ae2e)

I'm going to close this ticket off as the issues should now be resolved.
However, if you are still experiencing issues with Date Filtering on 8.6.0, (or above), then please get in touch.

Thanks again!
