### ISSUE TITLE
JS error appears after installation

### ISSUE THREAD

**Issue by RomanDolzhenko** [salesagility/SuiteCRM-Core#4]
Completed the installation of the CPM.
Database was created successfully. When we go to Public, we see the following JS errors:

![image](https://user-images.githubusercontent.com/24434079/113548349-0c8e1c00-95f8-11eb-91ff-07cd1fc764c3.png)

SuiteCRM Version used:
SuiteCRM 8.0-beta Releases
Environment name and version (e.g. MariaDB 10.1, PHP 7.4):
Operating System and version (e.g Centos 7):
Nginx, Node 10, Yarn 1.22.10, Angular CLI 11+

**Comment by Dillon-Brown** [comment]
Hi @RomanDolzhenko, the 404 here suggests that you may not have your webserver configured to allow re-writes. Can you please check that you have ```mod_rewrite``` enabled in apache with a configuration similar to this:

```
<VirtualHost *:80>
    ServerName domain.tld
    ServerAlias www.domain.tld

    DocumentRoot /var/www/project/public
    <Directory /var/www/project/public>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>
```

You can double check if this is a re-write problem by doing a request to: `https://<your_host>/index.php/api/graphql`. If you get an error message similar to the following and not a 404 it means its a problem with the rewrite.

![image](https://user-images.githubusercontent.com/1140849/113334155-44a50e80-931b-11eb-8381-872d06b04d0f.png)

**Comment by RomanDolzhenko** [comment]
Thanks it worked! Now i see this:
![image_2021_04_05T10_09_26_565Z](https://user-images.githubusercontent.com/24434079/113564963-e4f87d00-9612-11eb-9a92-3867c1e4a1c9.png)

**Comment by RomanDolzhenko** [comment]
Thanks, it's helped.
