### ISSUE TITLE
Install failed 

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM-Core#40]
#### Issue
Followed the install doc 
Install page is blank
Install via command line says success but still gives blank page

#### Expected Behavior
Install would work 

#### Actual Behavior
2021-12-06 17:54:52] install.INFO: Running step: create-env [] []
[2021-12-06 17:54:52] install.INFO: step: create-env | status: done [] []
[2021-12-06 17:54:52] install.INFO: step: create-env | messages: [] []
[2021-12-06 17:54:52] install.INFO: Created .env.local [] []
[2021-12-06 17:54:52] install.INFO: step: create-env | debug: no debug info [] []
[2021-12-06 17:54:52] install.INFO: Running step: run-legacy-install [] []
[2021-12-06 17:55:02] install.INFO: step: run-legacy-install | status: done [] []
[2021-12-06 17:55:02] install.INFO: step: run-legacy-install | messages: [] []
[2021-12-06 17:55:02] install.INFO: Legacy install successful [] []
[2021-12-06 17:55:02] install.INFO: step: run-legacy-install | debug: no debug info [] []
nothing in the prod log

#### Steps to Reproduce
Tried many times to unzip the file and install. Never get install page and command line says success but still blank 
<!DOCTYPE html><html lang="en"><head>
    <meta charset="utf-8">
    <title>SuiteCRM</title>
    <base href="">

    <meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0">
    <meta http-equiv="expires" content="0">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="icon" type="image/x-icon" href="dist/themes/suite8/images/favicon.ico">
<style>:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning:#ffc107;--danger:#dc3545;--light:#f8f9fa;--dark:#343a40;--breakpoint-xs:0;--breakpoint-sm:576px;--breakpoint-md:768px;--breakpoint-lg:992px;--breakpoint-xl:1200px;--font-family-sans-serif:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";--font-family-monospace:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;}*,:after,:before{box-sizing:border-box;}html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-webkit-tap-highlight-color:transparent;}body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff;}body{height:100%;margin:0;padding:0;border:none;background:#f5f5f5;}</style><link rel="stylesheet" href="dist/styles.5806247e63e952e4fef7.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="dist/styles.5806247e63e952e4fef7.css"></noscript></head>

<body>
<app-root></app-root>
<script src="dist/polyfills-es5.bd572d5a52462b4db2e4.js" nomodule defer></script><script src="dist/polyfills-es2015.b81ce80777ba591aef43.js" type="module"></script><script src="dist/main-es2015.4f73151df6d41fcd807b.js" type="module"></script><script src="dist/main-es5.4f73151df6d41fcd807b.js" nomodule defer></script>

</body></html>

#### Your Environment

* SuiteCRM Version used: 8.0 download 
* all 
* Centos 7, 10.3.29-MariaDB, PHP 7.3.28

**Comment by Mac-Rae** [comment]
Hi @wanesmith,

Can you confirm you have set permissions before and after the installation? A blank or partial page (Normally just the header) is a sign of incorrect permission.

The following commands are recommended by the [installation guide which for reference can be found here](https://docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing/).
```
find . -type d -not -perm 2755 -exec chmod 2755 {} \;
find . -type f -not -perm 0644 -exec chmod 0644 {} \;
find . ! -user www-data -exec chown www-data:www-data {} \;
chmod +x bin/console
```

Please let me know how you get on :+1:

**Comment by clemente-raposo** [comment]
Hi @wanesmith,

Thank you for trying out SuiteCRM  8.

To try do debug the problem. Could do the following please?

- on the `.env` file change `APP_ENV` to qa
- Open your browser's dev tools
- Open the network tab
- Go to the SuiteCRM 8 main page
- check the network tab

Are there any 404? On the `graphql` calls, see if there is any with an `errors` entry on the response

**Comment by wanesmith** [comment]
I followed the guide with changing the permissions did not skip any steps. @Mac-Rae 
root@candela crm]# find . -type d -not -perm 2755 -exec chmod 2755 {} \;
[root@candela crm]# find . -type f -not -perm 0644 -exec chmod 0644 {} \;
[root@candela crm]# find . ! -user apache  -exec chown apache  {} \;
[root@candela crm]# chmod +x bin/console
[root@candela crm]#

same blank page

**Comment by wanesmith** [comment]
@clemente-raposo ERROR Error: undefined
    Angular 4
    P https://crmdev.power-choice.com.au/crm/public/dist/polyfills-es2015.b81ce80777ba591aef43.js:1
    Angular 2
    v https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    _ https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    error https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    Angular 3
    v https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    _ https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    error https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    error https://crmdev.power-choice.com.au/crm/public/dist/node_modules_apollo_link-error_lib_bundle_esm_js-_3fab1-es2015.9b0ac6550a5dd80218be.js:1
    v https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    _ https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    error https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    error https://crmdev.power-choice.com.au/crm/public/dist/core_app_shell_src_bootstrap_ts-es2015.f1ac98f4222c1448c4f1.js:1
    RxJS 17
    a Angular
    invokeTask https://crmdev.power-choice.com.au/crm/public/dist/polyfills-es2015.b81ce80777ba591aef43.js:1
    onInvokeTask Angular
    invokeTask https://crmdev.power-choice.com.au/crm/public/dist/polyfills-es2015.b81ce80777ba591aef43.js:1
    runTask https://crmdev.power-choice.com.au/crm/public/dist/polyfills-es2015.b81ce80777ba591aef43.js:1
    invokeTask https://crmdev.power-choice.com.au/crm/public/dist/polyfills-es2015.b81ce80777ba591aef43.js:1
    m https://crmdev.power-choice.com.au/crm/public/dist/polyfills-es2015.b81ce80777ba591aef43.js:1
    g https://crmdev.power-choice.com.au/crm/public/dist/polyfills-es2015.b81ce80777ba591aef43.js:1
node_modules_angular_core_fesm2015_core_js-es2015.d7030c87f7f062fb36bc.js:1:59092

**Comment by clemente-raposo** [comment]
Hi @wanesmith,

Thank you for the feedback.

Yup, `graphql` its not supposed to be there, that is handled through url re-writes.

The issue you are seeing usually happens when there is some miss-configuration in apache's `mod_rewrite`.

Please have a look at the following section of the documentation [SuiteCRM 8 install guide - 1.3 Configuring URL re-writes](https://docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing/#_1_3_configuring_url_re_writes)

the following may also help:

https://community.suitecrm.com/t/suitecrm-8-beta-install-questions/79383/3?u=clemente.raposo

**Comment by wanesmith** [comment]
Thanks so much that worked I will close the issue. The instructions imply that the rewrite is not mandatory.
