### ISSUE TITLE
SuiteCRM 8 install - Port not properly set

### ISSUE THREAD

**Issue by clemente-raposo** [salesagility/SuiteCRM-Core#41]
#### Issue

When try to install some users have been having problems connecting their database.
This is usually the way the port is appended to the connection string.

it sometimes creates a connection string with `:` and not port, like `‘127.0.0.1:’`

See community forum thread: 
- https://community.suitecrm.com/t/install-database-connection-issue-with-suitecrm-8/82978/5?u=clemente.raposo

#### Expected Behavior

Admins should be able to use 'localhost' to connect to their database

#### Actual Behavior

Admins aren't able to use 'localhost' to connect to their database

#### Possible Fix

To fix this issue we should do the following:
- Make the db port entirely optional
- Remove the default from the db port
- if not port specified don't append the `:`

See possible fix in: https://community.suitecrm.com/t/install-database-connection-issue-with-suitecrm-8/82978/19?u=clemente.raposo

#### Steps to Reproduce

1. On command line install set the db host as `localhost`
2. Don't set any port on any port

#### Context

- See community forum: https://community.suitecrm.com/t/install-database-connection-issue-with-suitecrm-8/82978/15

#### Your Environment

* SuiteCRM Version used: 8.0.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4, 5.5.5-10.3.31-MariaDB-cll-lve
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mac-Rae** [comment]
Issue resolved with version 8.0.1
