### ISSUE TITLE
[8.5.0] - Opportunities filerting - Custom field (date) does not work in filter

### ISSUE THREAD

**Issue by TimmiORG** [salesagility/SuiteCRM-Core#412]
#### Issue
Custom field type date can't be used in filter on the Opportunity page.
![grafik](https://github.com/salesagility/SuiteCRM-Core/assets/979342/7a4da739-d701-4f3a-a9b4-65bb0a296d0f)

#### Expected Behavior
It should be possible to do the same filtering as in SuiteCRM 7.14.2
![grafik](https://github.com/salesagility/SuiteCRM-Core/assets/979342/b6c7c071-89a0-4b5c-b184-4d206b440089)

#### Actual Behavior
Filter does not work at all. No date picker and it is not possible to select anything.

#### Possible Fix
Not sure, but I would expect the same possibilities as in old SuiteCRM.

#### Steps to Reproduce
1. Create Custom files from type date for your opportunities.
2. Try to use it on the filter.

#### Context
I would rate this issue as high as it is not possible for us to filter the data for our reporting.

#### Your Environment

* SuiteCRM Version used: 8.5.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): latest Firefox
* Environment name and version (e.g. MySQL, PHP 7): 10.5.22-MariaDB,  PHP 8.2.13
* Operating System and version (e.g Ubuntu 16.04): Rocky Linux 9

**Comment by scicali** [comment]
duplicate #399

**Comment by johnM2401** [comment]
Hey @TimmiORG 
Thank you for raising this issue!

This should now be resolved as of the latest release (8.6.0)

See gif, showing some example searches using this field:

![dateFilter](https://github.com/salesagility/SuiteCRM-Core/assets/13675281/1bc9d472-4d78-4520-a89d-f39656e5ae2e)

I'm going to close this ticket off as the issues should now be resolved.
However, if you are still experiencing issues with Date Filtering on 8.6.0, (or above), then please get in touch.

Thanks again!
