### ISSUE TITLE
SuiteCRM 8.5.0 Unable to import value for Price in Product Import

### ISSUE THREAD

**Issue by billhallcode** [salesagility/SuiteCRM-Core#423]
#### Issue
Importing data into the Products module, when I map a value to the Price column the import fails immediately 

#### Expected Behavior
Rows import, rows with errors do not import and are notified post-import in a file

#### Actual Behavior
Immediate dialogue box displaying

'Import Error'

#### Steps to Reproduce

1. Create an import csv file
2. Two columns - Product Name (mandatory) Price
3. Add a value for Product Name and Price
4. Import file

#### My Environment
SuiteCRM v8.5.0
Running with 2 cpu and 8gb of memory
Debian 11.7
NGINX webserver
PHP-FPM 8.2
MySql 8.0.27-18

Browser: Chrome Version 120.0.6099.225 (Official Build) (64-bit)

**Comment by johnM2401** [comment]
Closing as fixed in 8.6.2 release.
Thank you for raising this!
