### ISSUE TITLE
For newly added user:  "Login credentials incorrect, please try again."

### ISSUE THREAD

**Issue by reggieeuser** [salesagility/SuiteCRM-Core#427]
**### Please check if a similar issue already exists or has been closed before.** 

Similar issues have been posted, but none exactly like this and no solutions offered.

**### Issue**

I installed a fresh SuiteCRM 8.5 instance, created two users, and imported ~50 Accounts and ~30 Contacts. The next day, I created two new users. I was unable to log in using either of the new users' credentials. I continually met the "Login credentials..." error above.

Rebuilding the database had no effect.

**### Expected Behavior**
Users entering correct credentials should be logged in.

**#### Actual Behavior**
Users are served the error message above and cannot use the site.

No relevant information appeared in either the SuiteCRM log or Apache2 logs. 

**#### Possible Fix**
No idea. I dropped back to version 7.14.

**#### Steps to Reproduce**

1.  Install 8.5
2.  Create admin & 1 other user.
3.  Go away over night.
4.  Create one or more additional users.
5.  Try to log in.

**#### Context**
This prevents users from accessing SuiteCRM at all.

If Version 8.5+ is to be considered for production use, this should be high priority.

#### Your Environment

SuiteCRM 8.5.0
Firefox 121.0.1/Chromium Version 120.0.6099.224
MySQL Ver 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
PHP 8.1.27
Ubuntu 22.04

**Comment by jack7anderson7** [comment]
Hi @reggieuser,

I am unable to replicate this issue.

Do you have any configuration setup for SAML/ LDAP? Sometimes this can be the result of failing logins.

Also, after creating an admin user & another user, did you keep the tab open and your session logged in while going away overnight?

If so, this might have been the result of your issues. As your session/ cookies will have exipred. You will have to hard refresh to clear/ reset cookies.

Thanks, 

Jack

**Comment by reggieeuser** [comment]
Hi Jack,

No config for SAML/LDAP.

Did not keep tab open.

Thanks for your thoughts, and when next I attempt to upgrade to v. 8.5 I'll keep them in mind. For now, we're still running 7.14...

Thanks again!

Reggie

**Comment by jack7anderson7** [comment]
Hi @reggieeuser  

As we are unable to replicate this issue and would need more information to continue, we will close this issue for now.

If you upgrade again and the issue persists please re-open this issue and give as much information as possible.

Thanks,

Jack
