### ISSUE TITLE
http://192.168.8.182/public/index.php on 8.5.1

### ISSUE THREAD

**Issue by stefanobiggi** [salesagility/SuiteCRM-Core#431]
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by stefanobiggi** [comment]
I consider the tool completely unreliable for real use. 
No support, no documentation, no debug, no test.
It is not possible for a product to have BUGS of this type for years.
In fact, the versions that are marketed (for a fee) are from 3 or 5 years ago.
It's fine for playing but it's not a tool that can be used in a company.

**Comment by mattlorimer** [comment]
I would suggest you use the community form if you are having issue with setting up https://community.suitecrm.com/ and you can refer to the documentation here https://docs.suitecrm.com/8.x/

**Comment by pgorod** [comment]
Conversation continues here:

https://community.suitecrm.com/t/http-192-168-8-182-public-index-php-on-8-5-1/91779
