### ISSUE TITLE
Invalid import file name when import Leads (Import File Template)

### ISSUE THREAD

**Issue by vnptphuyen** [salesagility/SuiteCRM-Core#44]
#### Issue

Invalid import file name when import Leads (Import File Template)
Step 1: Upload Import File

Select a file on your computer that contains the data that you would like to import, or download the template to get a head start on creating the import file.
Download Import File Template  Information

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 8.0.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by johnM2401** [comment]
Hey there, 

What sort of filename does your Import file have?

The Import page details that only Alphanumberic Characters, as well as ".", "-" and "_" will be accepted.

![image](https://user-images.githubusercontent.com/13675281/146773085-0c4ddbeb-9daa-40b2-9b24-a8215d05cdec.png)


Does your filename perhaps contain invalid characters?

**Comment by vnptphuyen** [comment]
Thanks you. Problem solved.
