### ISSUE TITLE
V8.5.0 Select All - Bulk Export fails on Accts, Contacts & Products with  ‘Unexpected Error when calling action’ message

### ISSUE THREAD

**Issue by ggraynoth** [salesagility/SuiteCRM-Core#442]
In Accounts, Contacts and Products (may also be an issue in other modules but not tested), when you click on the Select check box, in the list view and select all records and then go into Bulk Action and try to export the records, the system error with an Unexpected Error when calling action’ message. This prevents export of the full database for that module.

#### Issue
You should be able to select all and export without any failure. This fails regardless of database size (no. of records) and is a bug, as this should work.

#### Expected Behavior
Select all records and Bulk action Export should produce the Excel CSV export file of the database selected.

#### Actual Behavior
The system displays the error as defined above and aborts the export. No file is created.

#### Possible Fix
As a work around, which exemplifies why this is a bug when taking the 'select all' path, is to filter the database and then do the same thing on the filtered selection. This then works. So, as a workaround, we have created a bogus 'type ' field
 in the case of  Accounts and similar for contacts and products, then created an account with a type equal to the  bogus value. This  can be used within the filter function. We then filter by selecting all Account types except for the bogus value in the drop down and create a filter, which is effectively all records except for the one with the bogus type.

Then select all and bulk export and it works fine.

Which would indicate that there is a code path which is failing, when all records with no filter is attempted. 

#### Steps to Reproduce
Go into the accounts module, select all records in the list view and then try to do a bulk action, Export. This will fail as per the above.

Redo using the filter method highlighted above and it will work.

#### Context
As we had a fault with the bounceback feature, which meant it was not working, no contacts were tagged as bounced invalid or bounced other. We have now fixed this. however, whilst this was happening, we needed to export the contact database and match the bounced contacts and reimport, which we couldn't do by selecting and exporting all contact records. We had to find the filter work-around and do it that way.

These features should work as they absorb a lot of time to identify the work-around, however the bug still persists. There are also reports in the Forum that other functions fail, where Select All does not work for bulk actions for no apparent reason. These may be linked but we have not had reason to use these functions.

#### Your Environment
SuiteCRM 8.5.0
MariaDB 10.5.22
PHP 8.1.26

**Comment by rsteinig** [comment]
Local project overwrite done by me of wrong .php file fixed that issue for me. Somehow the request does ignore the "all" use-case. Would be better, to send a valid "all" param instead of guessing it before an exception is thrown.

`<?php
/**
 * SuiteCRM is a customer relationship management program developed by SalesAgility Ltd.
 * Copyright (C) 2021 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SALESAGILITY, SALESAGILITY DISCLAIMS THE
 * WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License
 * version 3, these Appropriate Legal Notices must retain the display of the
 * "Supercharged by SuiteCRM" logo. If the display of the logos is not reasonably
 * feasible for technical reasons, the Appropriate Legal Notices must display
 * the words "Supercharged by SuiteCRM".
 */


namespace App\Process\Service\BulkActions;

use ApiPlatform\Core\Exception\InvalidArgumentException;
use App\Data\LegacyHandler\FilterMapper\LegacyFilterMapper;
use App\Module\Service\ModuleNameMapperInterface;
use App\Process\Entity\Process;
use App\Process\Service\ProcessHandlerInterface;

class CsvExportBulkAction implements ProcessHandlerInterface
{
    protected const MSG_OPTIONS_NOT_FOUND = 'Process options is not defined';
    protected const PROCESS_TYPE = 'bulk-export';

    /**
     * @var ModuleNameMapperInterface
     */
    private $moduleNameMapper;

    /**
     * @var LegacyFilterMapper
     */
    private $legacyFilterMapper;

    /**
     * CsvExportBulkAction constructor.
     * @param ModuleNameMapperInterface $moduleNameMapper
     * @param LegacyFilterMapper $legacyFilterMapper
     */
    public function __construct(ModuleNameMapperInterface $moduleNameMapper, LegacyFilterMapper $legacyFilterMapper)
    {
        $this->moduleNameMapper = $moduleNameMapper;
        $this->legacyFilterMapper = $legacyFilterMapper;
    }

    /**
     * @inheritDoc
     */
    public function getProcessType(): string
    {
        return self::PROCESS_TYPE;
    }

    /**
     * @inheritDoc
     */
    public function requiredAuthRole(): string
    {
        return 'ROLE_USER';
    }

    /**
     * @inheritDoc
     */
    public function getRequiredACLs(Process $process): array
    {
        $options = $process->getOptions();
        $module = $options['module'] ?? '';
        $ids = $options['ids'] ?? [];

        return [
            $module => [
                [
                    'action' => 'export',
                    'ids' => $ids
                ]
            ]
        ];
    }

    /**
     * @inheritDoc
     */
    public function configure(Process $process): void
    {
        //This process is synchronous
        //We aren't going to store a record on db
        //thus we will use process type as the id
        $process->setId(self::PROCESS_TYPE);
        $process->setAsync(false);
    }

    /**
     * @inheritDoc
     */
    public function validate(Process $process): void
    {
        if (empty($process->getOptions())) {
            throw new InvalidArgumentException(self::MSG_OPTIONS_NOT_FOUND);
        }

        $options = $process->getOptions();

        if (empty($options['module']) || empty($options['action'])) {
            throw new InvalidArgumentException(self::MSG_OPTIONS_NOT_FOUND);
        }

        if (empty($options['fields'])) {
            throw new InvalidArgumentException(self::MSG_OPTIONS_NOT_FOUND);
        }

        $all = empty($options['ids']) && is_array($options['criteria']) && !empty($options['fields']);
        if (!$all && empty($options['ids']) && empty($options['criteria'])) {
            throw new InvalidArgumentException(self::MSG_OPTIONS_NOT_FOUND);
        } else {
            $options['all'] = $all;
            $process->setOptions($options);
        }
    }

    /**
     * @inheritDoc
     */
    public function run(Process $process)
    {
        $options = $process->getOptions();

        $responseData = $this->getDownloadData($options);

        $process->setStatus('success');
        $process->setMessages([]);
        $process->setData($responseData);
    }

    /**
     * @param array|null $options
     * @return array
     */
    protected function getDownloadData(?array $options): array
    {
        $responseData = [
            'handler' => 'export',
            'params' => [
                'url' => 'legacy/index.php?entryPoint=export',
                'formData' => []
            ]
        ];

        if (!empty($options['ids']) || !empty($options['all'])) {
            $responseData = $this->getIdBasedRequestData($options, $responseData);

            return $responseData;
        }

        if (!empty($options['criteria'])) {
            $responseData = $this->getCriteriaBasedRequestData($options, $responseData);
        }

        return $responseData;
    }

    /**
     * Get request data based on a list of ids
     * @param array|null $options
     * @param array $responseData
     * @return array
     */
    protected function getIdBasedRequestData(?array $options, array $responseData): array
    {
        $responseData['params']['formData'] = [
            'uid' => $options['all'] ? '' : implode(',', $options['ids']),
            'module' => $this->moduleNameMapper->toLegacy($options['module']),
            'action' => 'index',
            'all' => $options['all'],
        ];

        return $responseData;
    }

    /**
     * Get Request data based on a search criteria
     * @param array|null $options
     * @param array $responseData
     * @return array
     */
    protected function getCriteriaBasedRequestData(?array $options, array $responseData): array
    {
        $responseData['params']['url'] .= '&module=' . $this->moduleNameMapper->toLegacy($options['module']);

        $downloadData = [
            'module' => $this->moduleNameMapper->toLegacy($options['module']),
            'action' => 'index',
            "searchFormTab" => "advanced_search",
            "query" => "true",
            "saved_search_name" => "",
            "search_module" => "",
            "saved_search_action" => "",
            "displayColumns" => strtoupper(implode('|', $options['fields'])),
            "orderBy" => strtoupper($this->legacyFilterMapper->getOrderBy($options['sort'])),
            "sortOrder" => $this->legacyFilterMapper->getSortOrder($options['sort']),
            "button" => "Search"
        ];

        $type = $options['criteria']['type'] ?? 'advanced';

        $mapped = $this->legacyFilterMapper->mapFilters($options['criteria'], $type);
        $downloadData = array_merge($downloadData, $mapped);

        $responseData['params']['formData'] = [
            'current_post' => json_encode($downloadData)
        ];

        return $responseData;
    }
}
`

**Comment by ggraynoth** [comment]
Thank you. 

However did not work for our back-up or prod installations.

We did the code update exactly as defined and saved the CsvExportBulkAction.php after having taken a back-up. Then double checked that the new code was in place.

Cleared the browser cache and logged back in to SuiteCRM - same result - 'Unexpected Error when calling action' when trying to export all contacts or accounts.

Thanks anyway - hope this helped someone. The code does look sound, although I am no expert.

**Comment by rsteinig** [comment]
Ok, I am sorry, it didn't work out for you, Just tried again on my local instance by just swapping the files and it run... Maybe you can use some local Xdebug session and check out, if the "validate" method gets executed or not. Good luck.

**Comment by ggraynoth** [comment]
No worries. will debug and see if that provides any clue.



________________________________
