### ISSUE TITLE
Full Release Archive does not contain all releases

### ISSUE THREAD

**Issue by kale1d0code** [salesagility/SuiteCRM-Core#469]
#### Issue

To Click on Full Release Archive on website and am taken to a list of releases and upgrade packages.
some are missing

#### Expected Behavior

To Click on Full Release Archive on website and be able to choose to update between any version or install any version

#### Actual Behavior

Click on Full Release Archive, am taken to sourceforge website which doesn't contain every package released by salesagility for suitecrm

#### Steps to Reproduce

1. Navigate to https://suitecrm.com/releases/
2. Click "Full Release Archive"
3.
4.

#### Context

I am attempting to update a brand new suite 7 instance directly to suite 8.2.4
so I can figure out how to revert SuiteCRM 8.2.4 to SuiteCRM 7.x

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4 & PHP 8.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 23.10

**Comment by pgorod** [comment]
I see [SuiteCRM-8.2.4.zip](https://sourceforge.net/projects/suitecrm/files/SuiteCRM-8.2.4.zip/download) on that list, which one exactly do you find missing?

**Comment by kale1d0code** [comment]
Hi, Apologies, I was expecting an update / migration package from 7.x directly to 8.2.4. however there seems to have been some miscommunication and the system I'm looking into was setup on 8.2.4 and I'm now under the impression there never was such a migration / updateI'll close thisOn 30 Apr 2024 14:50, pgorod ***@***.***> wrote:
I see SuiteCRM-8.2.4.zip on that list, which one exactly do you find missing?
