### ISSUE TITLE
[8.6.0] Filters don't provide any dropdown option values

### ISSUE THREAD

**Issue by vladaman** [salesagility/SuiteCRM-Core#470]
#### Issue
After upgrading from SuiteCRM 8.4.0 to 8.6.0, the list view filters dropdown is not showing any options. This functionality was working as expected in the previous version, and the absence of dropdown options is impeding the ability to effectively filter list views.

#### Expected Behavior
When selecting filters in any list view, the dropdown should provide a list of filter options to choose from.

#### Actual Behavior
The dropdown under Filters in list views is not offering any options post-upgrade. Attached screenshot shows that there is an item in list view and the option should be offered in Filter.

#### Steps to Reproduce
1. Log in to SuiteCRM 8.6.0.
2. Navigate to any module's list view (e.g., Accounts, Contacts).
3. Click on 'Filters' to expand filter options.
4. Try to select a filter from the dropdown menu.
5. Observe that no options are presented in the dropdown.

#### Context
This bug is significantly affecting the user experience as it prevents efficient filtering in list views, which is essential for managing and navigating through records.

#### Your Environment
* SuiteCRM Version used: 8.6.0
* Browser name and version: Brave Browser

![Screenshot from 2024-05-01 08-42-20](https://github.com/salesagility/SuiteCRM-Core/assets/907206/0fde4d6d-58c1-4fae-a33d-cb9e72ce2c78)

**Comment by johnM2401** [comment]
Hey @vladaman 
Thank you for getting in touch!


hmmm, I've been giving this a try but have been unable to replicate so far, i'm afraid.
I've tried:
- Core Dropdowns
- Custom Dropdowns with Special Characters in the Values
- Dropdowns on an Upgraded instance

But no luck yet


Would you be able to share some more information?

Such as:

- Which PHP version are you using?
- What commands were run when upgrading? (ie: Both Upgrade and upgrade-finalize, with permissions re-set?)
- Do you know if any Core CRM dropdowns are filterable, or do these have the same issue?


If you haven't already, it might be worth:
- Re-saving the view in Studio as this appears to have solved issues for another user (raised: https://github.com/salesagility/SuiteCRM-Core/issues/468)
- Run Repair and Rebuild & Re-set Permissions


Please let us know how you get on, or if you have further information.
Thank you!

**Comment by vladaman** [comment]
I just noticed one more thing - our API has also stopped working and the following PHP file is not being interpreted when I test it. Other php files are interpreted. Not sure if it's related. (see https://github.com/salesagility/SuiteCRM-Core/issues/472)

* PHP 8.1.2-1ubuntu2.14
* I tried to run repair and also .htaccess repair.
* I tried to open the list view in Studio and save it again
* I don't see any graphql call which would get the values for the filters. They seem to be empty. Is it supposed to fetch data from server for the filter values? When I try to change the value it does not perform any server-side call

Upgrade has been done as `./bin/console suitecrm:app:upgrade -t suite_8.6.0`  under sudo (since there is always problem to do with with proper permissions) and then all permissions has been set to `chown www-data * -R ./`

**Comment by johnM2401** [comment]
Hey @vladaman 
Thanks for getting back to us


Regarding the Filter values, I believe most Enum-type fields will populate from the Enum-field's selected Dropdown List
(ie: The one selected for the field in Studio)


<br>

Regarding your issues, at the moment, the only thing I can think to ask is:

You mentioned that you have run ``` "./bin/console suitecrm:app:upgrade -t suite_8.6.0"```
Apologies if you already have, but have you run the upgrade-finalize command afterwards?

It follows the format:
```./bin/console suitecrm:app:upgrade-finalize -t "<same zip used as upgrade command>"```

There's a helpful forum post I've found that notes the general steps to take:
https://community.suitecrm.com/t/migration-from-8-5-1-to-8-6/92376/5
(ie: Set Permissions -> Upgrade Step -> Reset Permissions -> Upgrade-finalize step -> Reset Permissions)

<br>

If that fails, you could also try clearing Symfony cache by running:
```./bin/console cache:clear``` 
In the Root of the Suite8 project folder


<br>

Please let us know how you get on

Thank you again!

**Comment by clemente-raposo** [comment]
Hi @vladaman 

We've re-tested this issue on 8.6.1 by creating a new enum field on the accounts module using studio and adding in to detail view, listview and advanced filter. It seems to work as expected ( see the following video). 

Please consider upgrading. If the issue still occurs after the upgrade, please re-open this issue.

Closing the issue.

https://github.com/salesagility/SuiteCRM-Core/assets/1140849/196a3865-ce1e-491d-a115-608ac09c8460
