### ISSUE TITLE
Document filename(file) not showing in Subpanels

### ISSUE THREAD

**Issue by Vercin1001** [salesagility/SuiteCRM-Core#473]
#### Issue

Document filename(file) does not show in subpanels under any module. Ex: opportunities, accounts, contracts, etc...
#### Expected Behavior

Document filename(file) should show in subpanel and should let you download by clicking it.
#### Actual Behavior

The filename(file) column is blank.
#### Possible Fix

Might be related to this issue.
[#168](https://github.com/salesagility/SuiteCRM-Core/issues/168)
#### Steps to Reproduce

1. Use the demo and click on any Module related to Documents for Ex. Opportunity.
2. Click on the Document subpanel.
3. Create a document if none
4. All filename columns are blank

![image](https://github.com/salesagility/SuiteCRM-Core/assets/86845172/cd1ae659-40b6-4a92-80d2-2a018d3ffeac)
![image](https://github.com/salesagility/SuiteCRM-Core/assets/86845172/bd526302-5315-4e7c-a6af-b93f75b571c7)
![image](https://github.com/salesagility/SuiteCRM-Core/assets/86845172/f3c6225d-41e0-46b6-a55e-95b5a433ad3d)

#### Your Environment

* ALL DEMO ENVIROMENT Suitecrm 8.6

**Comment by pgorod** [comment]
Did you try applying the fix from #168 ?

**Comment by pgorod** [comment]
Did you try applying the fix from #168 ?

**Comment by Vercin1001** [comment]
@pgorod Yes, we just did yesterdary and it fixes the email on the contacts subpannel but not on documents, here is a screanshot of our local env.
![image](https://github.com/salesagility/SuiteCRM-Core/assets/86845172/d918e6d8-3b31-46c6-9b76-10e39b889ad7)

**Comment by LikhithR14** [comment]
where you able to fix the issue for Opportunity Document subpanel?

**Comment by Vercin1001** [comment]
@LikhithR14 hey no, right now i dont have the time to fix it sorry
