### ISSUE TITLE
Editing related quote from opportunity subpanel gives you are not authorized

### ISSUE THREAD

**Issue by abuzarfaris** [salesagility/SuiteCRM-Core#481]
![image](https://github.com/salesagility/SuiteCRM-Core/assets/29313328/9f2425c7-13ec-4798-998c-e45ef1f6abf3)

#### Expected Behavior

Pressing the edit button should open quote editview

#### Actual Behavior
Displays prompt with "You are not authorized to view this page. Please contact your system administrator."

#### Steps to Reproduce

1. Go to an opportunity record
2. View the quotes subpanel. if does not quote exists create or relate one
3. Click the Edit button and the error occurs
4.

#### Your Environment

* SuiteCRM Version used: 8.6 on suite8demo
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
I believe I had fixed this already, let me go looking for it...

**Comment by abuzarfaris** [comment]
@pgorod I checked the demo version and it still had the  issue
