### ISSUE TITLE
PHP Fatal error:  Uncaught RuntimeException: Unable to create the Doctrine Proxy directory on clean install

### ISSUE THREAD

**Issue by ViralAgency** [salesagility/SuiteCRM-Core#496]
### Issue

Hi SalesAgility,

I'm testing this new version but I'm encountering numerous problems, the most important of which is related to the "Repair & Rebuild" function which causes the user to log out, the appearance of errors such as "Unexpected error when calling action" and the stack trace which I attach it below.

```
[31-May-2024 22:43:47 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to create the Doctrine Proxy directory "/var/www/html/cache/prod/prod/doctrine/orm/Proxies". in /var/www/html/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:56
Stack trace:
#0 /var/www/html/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(98): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp()
#1 /var/www/html/core/backend/Engine/Service/Extensions/ExtensionAssetCacheWarmupDecorator.php(87): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp()
#2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(580): App\Engine\Service\Extensions\ExtensionAssetCacheWarmupDecorator->warmUp()
#3 /var/www/html/core/backend/Kernel.php(124): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#4 /var/www/html/public/index.php(39): App\Kernel->getLegacyRoute()
#5 {main}
  thrown in /var/www/html/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php on line 56
```

Reporting the problem in the forum did not lead to appreciable results. Permissions on files and folders have been checked properly. 

Solutions proposed by various Symphony forums, such as editing the doctrine.yaml configuration file not helped resolve the issue.

My System configuration is:
OS: Ubuntu 24.04
PHP: 8.2.19
MYSQL:  8.0.37

### Possible Fix

I haven't no more ideas.

### Steps to Reproduce the Issue

```bash
1. Install on fresh OS (in my case, i work on dockerized system)
2. Go to Administration panel->Repair->Quick rebuild & repair
3. Check /var/log/php/php_errors.php
```

### Version

8.6.0

### What browser are you currently using?

Chrome

### Environment Information

MySql 8.0.37, PHP 8.2.19

### Operating System and Version

Ubuntu 24.04

**Comment by chris001** [comment]
For a test, when you run the official bitnami suite  8 docker container, does it work?  It should.

Did you run installer from command line (CLI) or thru the web browser?

Are you running PHP-FPM execution mode?
If yes, is this PHP-FPM setup by the container, by you manually, or by a script?

All php modules installed and enabled?

The user you're running the PHP process under, is it the same user that you installed Suite 8 files as?

**Comment by ViralAgency** [comment]
Hi @chris001, thanks for your attention.

1) I'm testing the official bitnami suite 8 docker container, i 'll let you know very soon if the problem was in my docker configuration.

2) I have installed in both ways.

3) No. I have

**Comment by ViralAgency** [comment]
Thanks for your quickly answers @chris001.

Step-by-step:

1. I have installed the official bitnami image and works only when works in non-persistence mode (bind mount) from Docker.
The problem now seems to be related to permissions across Docker volume and suitecrm, a potential incompatibility between.

2. I have installed in both ways: from cli, everything t's ok, with user interface i have firstly return "missing-library" (soap), but now is ok, no installation error log.

3. Thanks for the suggestion: in fact, i had php8.2-fpm package and "a2enconf php8.2-fpm" directive activated, but is the same with or without these. PHP-FPM was default configured.

4. Did you mean SuiteCRM mudules or PHP modules? In the first case, yes, 'cause i start from a brend new installation, in the second one, no missing modules log.

5. SuiteCRM was instllaled from UX (www-data), and from CLI (root), nut same result.

Thank you for your support.

**Comment by chris001** [comment]
What happens when you reset the permissions and owner, of all Suite files, from inside the bitnami Suite 8 docker container?
```
cd /opt/bitnami/suitecrm
sudo find . -type d -not -perm 02750 -exec chmod 02750 {} \;
sudo find . -type f -not -perm 0640 -exec chmod 0640 {} \;
sudo find . ! -user daemon -exec chown daemon:daemon {} \;
sudo chmod u=rwx,g=rx ./bin/console   #Suite 8
sudo chmod u=rwx,g=rx ./vendor/bin/*  #Suite 7
sudo ./bin/console cache:clear
```

Next, what happens when you run one of these from command line?  They do Quick Repair and Rebuild, without need to log in:

1.
https://gist.github.com/esimonetti/9ca21b15dc47565b12ee73e2352da549

2.
https://github.com/esimonetti/toothpaste

**Comment by ViralAgency** [comment]
Thanks for your suggestion @chris001.

I have clarified further about this problem and asked more suggestions around the world (see [this](https://stackoverflow.com/questions/78565899/php-fatal-error-uncaught-runtimeexception-unable-to-create-the-doctrine-proxy) post on StackOverflow, please upvote if is useful for you).

The problem had its origins on docker bind-mount system, probably for permissions issues between host machine and container.

Solution is “to esclude” /cache folder from docker-compose.yml bind mount like below:

```
services:
  suitecrm:
    container_name: suitecrm
    build: .
    volumes:
      #SuiteCRM Application Folder
      - ./www:/var/www/html:delegated
      - /var/www/html/cache/   #Another volume with cache subfolder inside the existing one
```
In this way cache subfolder can re-create proxy classes on rebuild and repair.

Thanks.
