### ISSUE TITLE
Upload max size error on install

### ISSUE THREAD

**Issue by MauriceHandwerker** [salesagility/SuiteCRM-Core#500]
### Issue

When installing SuiteCRM 8 i have the upload_max_size error saying that it needs to be atleast 6MB.
I changed everything in the php.ini`s so it should work. 

Now it says that the upload_max_size should be 6MB and I currently have 4GB (thats what I set in the php.ini)
![image](https://github.com/salesagility/SuiteCRM-Core/assets/66009198/73fe9bf4-d642-432a-9458-6ee7e5852b6b)

For some reason it doesent work. 
I tried many different sizes (6MB, 1GB, 5GB, 10MB) nothing worked.

And I restarted apache on every change to the php.ini. 
(I changed the post_max_size to the same as the upload_max_size everytime)

### Steps to Reproduce the Issue

```bash
1. Follow the instructions in the documentation?
```

### Version

8.6.0

### What browser are you currently using?

Chrome

### Browser Version

Chrome (latest version)

### Environment Information

MariaDB (latest), PHP 8.2

### Operating System and Version

Debian 12

**Comment by pgorod** [comment]
What is the full path to the php.ini that you edited?

You need to make sure you're editing the correct one, there can be several.

**Comment by MauriceHandwerker** [comment]
I checked that already with the phpinfo. 
``/etc/php/8.2/apache/php.ini``
and
``/etc/php/8.2/cli/php.ini``

**Comment by chris001** [comment]
1. Try these values in your `php.ini` and report back your results:
```
post_max_size = 100M
upload_max_filesize = 100M
memory_limit = 512M
file_uploads = On
max_execution_time = 180
```
And reload apache with the command: 
`sudo systemctl reload apache2`

2. If that fails, then create a new file `.user.ini`, copy paste the values into that file, save it in the base directory of your Suite install, in the same directory containing the file `index.php`.  Wait up to 5 minutes for the settings to take effect - apache only detects values from `.user.ini` every 5 minutes.  Report back your results.

**Comment by shubham-pawar** [comment]
### For Apache:
```
sudo systemctl restart apache2
```

### For Nginx with PHP-FPM:
```
sudo systemctl restart php8.2-fpm
```

**Comment by mattlorimer** [comment]
Closed as more suitable for [community form](https://community.suitecrm.com/)
