### ISSUE TITLE
Error fetching metadata caused by disabling default (installed) language file

### ISSUE THREAD

**Issue by veggydawson** [salesagility/SuiteCRM-Core#53]
#### Issue
After installing another language file (English (United Kingdom - en_GB in this case) moving the default language file (US English) into the 'disabled' column from the **_Admin->Language_** page [(](/#/administration/Languages?view=default) causes errors on subsequent page loads on many pages.

For example trying to add a new contact results in an "Error occurred while fetching metadata".

Once that error has been triggered the UI then fails to respond correctly.  The drop-down menus drop on hover-over but as soon as the mouse moves, the sub-menu disappears making it impossible to navigate with a mouse.

The only way to recover the situation is to logout (xxx.com/logout) and then login in again.  The "Admin" pages, luckily, do continue to work.

#### Expected Behavior
The system should continue to operate with out throwing an error and the UI should continue to work properly.

#### Actual Behavior
An error is thrown and the system becomes unusable without re-enabling the language

#### Steps to Reproduce

1. Go to Admin area (/#/administration/index)
2. Select **Languages**  (#/administration/Languages?view=default)
3. Move English (US) into the "Disabled Languages" column
4. Click "Save" button
5. Navigate to another page, "Create Contact" for example.
6. Error is thrown and the UI breaks.

#### Context
This is not a huge operational problem if you are aware of the issue, however it caught me for a while on a fresh install during the initial setup phase. New users may become frustrated when trying to keep the install tidy with only the modules/languages/locales etc that they want to have installed. 

I think it is a medium priority bug due to the devastating effect it has on the overall system. 

#### Your Environment
Suite CRM 8.0.1
All browsers are affected.
PHP 7.4
MariaDB
Ubuntu Server 20.04

**Comment by Mac-Rae** [comment]
Hi @veggydawson,

Confirmed in 8.0 >
