### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by CSC-DEVV** [salesagility/SuiteCRM-Core#535]
### Issue

DELETE {{suitecrm.url}}legacy/Api/V8/module/Accounts/{id}
When I run this api it returns
<h1>Slim Application Error</h1>
    <p>The application could not run because of the following error:</p>
    <h2>Details</h2>
    <div><strong>Type:</strong> Error</div>
    <div><strong>Message:</strong> Call to a member function call_custom_logic() on bool</div>
    <div><strong>File:</strong> /var/www/html/public/legacy/data/Relationships/SugarRelationship.php</div>
    <div><strong>Line:</strong> 423</div>

### Steps to Reproduce the Issue

```bash
1.
2.
3.
...
```

### Version

8.7.1

### What browser are you currently using?

Microsoft Edge

### Environment Information

8.2

### Operating System and Version

Ubuntu

**Comment by johnM2401** [comment]
Hey!

Thank you for getting in touch!

I've given this a few tries locally on 8.6.1, but I've been unable to replicate so far, I'm afraid

See for example, I'm able to delete an account via the V8 API:
![image](https://github.com/user-attachments/assets/8dd5f091-0a75-4bab-afd2-b9f19e310250)


Could you share some more information on your environment?

ie:
- What version of MySQL / MariaDB / etc are you using?
- Does this error happen for just Accounts, or you unable to delete any module record via API?
- Does your Accounts module have any custom Fields or relationships? (either via Code or via studio)
- Do you have any Workflows or Logic hooks that affect the Accounts module?
- Do you have any further steps to replicate, that might help with replication?

Thank you again!

**Comment by mattlorimer** [comment]
Closed as no update, likely issue related to customisation
