### ISSUE TITLE
NG Frontend: Ranged Search Options not work for Numeric Type Field

### ISSUE THREAD

**Issue by scicali** [salesagility/SuiteCRM-Core#54]
Issue
Ranged Search Options not work for Numeric Type Field, work in legacy frontend

Expected Behavior
Ranged Search Option must appear in filters when enable it

Steps to Reproduce
    Install as per instructions, with demo data
    Enable Ranged Search Option for a Currency/Int/Numeric field
    repair and rebuild from administration
    ./bin/console cache:clear
    Ranged Search Options not appear in filter

Your Environment
    SuiteCRM Version used: 8.0.1
    Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 94
    Environment name and version (e.g. MySQL, PHP 7): php 7.4
    Operating System and version (e.g Ubuntu 16.04): debian 11

**Comment by BastianHammer** [comment]
Still the same issue on 8.5. as it seems:
![image](https://github.com/salesagility/SuiteCRM-Core/assets/96183835/37b12f25-a8a8-4b96-bbf4-d76270c5d462)
