### ISSUE TITLE
Redirect to last URL after login

### ISSUE THREAD

**Issue by Mac-Rae** [salesagility/SuiteCRM-Core#56]
#### Issue

When using a location-specific URL, and unauthorised, you are taken to the login page. Once logged in and now authorised you are not redirected to the location-specific URL from before only taken directly to the Dashboard.

#### Possible Fix

Only redirect to Homepage after login if URL from before you are redirected to the homepage was invalid.

#### Steps to Reproduce

1. Try to go to https://suite8demo.suiteondemand.com/#/home/about
2. Once redirected to the login page, enter will, will as credentials
3. See that once logged in you are not taken to about page but only do homepage

#### Context

Lowers efficiency when using CRM compared to Suite7

#### Your Environment

* SuiteCRM Version used: 8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 97.0.4692.71
* Environment name and version (e.g. MySQL, PHP 7): MariaDB PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04

**Comment by myfluxi** [comment]
There is a related annoying issue where the current session is repeatedly deleted unnecessarily when logging out/being logged out. Here is a fix for this (note, I reverted some bogus patch in it and I run Symfony 5.4). Basically it's just a cookie that's honoured during login.

https://github.com/myfluxi/SuiteCRM-Core/commit/943f0a8a1192a8f6beb2d3f92a7eb7fd40dffe1c
