### ISSUE TITLE
History subpanel with blank columns except subject

### ISSUE THREAD

**Issue by jssilva25** [salesagility/SuiteCRM-Core#58]
Installed v8 on a separate instance for testing. Then, restored a dump from my v7 instance.

After importing an email and unfolding the history subpanel, on accounts, contacts, leads and I guess other modules, all columns have blank content (status, contact, dates) with exception of subject.

The behaviour is the same for existing emails on the database restored from v7.

Please note v7 subpanel on screenshot has been slightly customised  with column  Date RxTx addition.

EDIT: As an additional comment, I think the Date RxTx column, which is the date an email (or a call) was sent or received, is an essential information whereas Date Created or Modified is irrelevant, at least for me.

#### Expected Behavior
History subpanel columns should be populated with status, contact, date modified, date created, due date.

#### Actual Behavior
History subpanel columns are blank with exception of subject

#### Steps to Reproduce
1. Call account or contact that has history
2. Unfold history panel
3. History emails columns are blank with exception of subject

#### Context
It's serious if I cannot see the dates and contact relevant to a history email or call

#### Your Environment
* SuiteCRM Version used: v8.01
* Safari v15.2
* MariaDB v10.15.13, PHP v7.4.27, apache v2.4
* Operating System and version (e.g Ubuntu 16.04): macOS 10.15.7

![Suitecrm v7 history](https://user-images.githubusercontent.com/8608497/151075411-ad03d482-a0d4-41ba-a209-a80cbb8bba0b.png)
![Suitecrm v8 history](https://user-images.githubusercontent.com/8608497/151075431-058ef6a0-5f7f-46c9-a945-dc9a59523a2a.png)

**Comment by johnM2401** [comment]
Hey there, 

I've given this a quick test, and I appear to be unable to replicate, I'm afraid
![image](https://user-images.githubusercontent.com/13675281/154106695-7a1d2360-9354-4332-bf79-336081ca4c09.png)

<br>

Would you be able to confirm some things for me?:

- Do you know if this functionality works, without the custom field?
(if you are not sure, could you perhaps share what customizations were made, so we can try to replicate this further on our end?)

- You mention that you are on 8.0.1, have you tried this on the most recent version? (8.0.3)
I believe SuiteCRM 7.12.3 is used as the backend of 8.0.3, and there were a few changes around Emails in this version that may assist in resolving this

- Do you get any errors in the SuiteCRM.log or your PHP Error log that appear to be related?

Thanks!

**Comment by pgorod** [comment]
> Installed v8 on a separate instance for testing. Then, restored a dump from my v7 instance.

This doesn't sound like a supported way of installing SuiteCRM.... at all.

**Comment by jssilva25** [comment]
Well, it was just for a quick test.
Sorry for the trouble, I'll try again when it's ready.
