### ISSUE TITLE
Bulk select option is not showing while adding records through subpanel in suitecrm8

### ISSUE THREAD

**Issue by jyotiraghav93** [salesagility/SuiteCRM-Core#60]
Bulk select option is not showing while adding records through subpanel in suitecrm8

**Comment by jyotiraghav93** [comment]
I have suitecrm 8 already installed , but it is missing some features . It seems i need to migrate to sugarcrm .
One of the basic feature not available in suitecrm 8 is that bulk select option is not available in popup view while linking the records from the subpanel.
Please let me know if this option is available in any other suitecrm 8 releases?

**Comment by Mac-Rae** [comment]
Hi @jyotiraghav93,

Could you give us a tad more detail as to the feature that's "missing"?

Mass Update from the list view allows editing of all records in that record at once.
We currently are working to return the feature in which you are able to change the security groups via Mass Update also!
