### ISSUE TITLE
Calls/Meetings start date is not corrected for timezone in list view

### ISSUE THREAD

**Issue by mcube27** [salesagility/SuiteCRM-Core#61]
#### Issue
When I create a Meeting or a Call, I can input start time in my timezone (Europe/Zurich).
It is saved in UTC.
If I go back to the detail view, it is at the time I planned.

But if I go to the list view, the start date is UTC.

#### Expected Behavior
Everywhere my timezone is used.

#### Actual Behavior
List views are UTC and not my timezone

#### Steps to Reproduce
Check you timezone in not UTC
Create Meeting or Call
Check list of Meetings

#### Your Environment

* SuiteCRM Version used: 8.0.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 96.0.2 (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): Php 7.2, MySql
* Operating System and version (e.g Ubuntu 16.04): Windows and linux

**Comment by scicali** [comment]
Same issue, in legacy frontend use correct timezone

**Comment by scicali** [comment]
Confirmed in lastest (8.1)

**Comment by cadonovan** [comment]
I have the same issue happening in tasks detailed view. If I add a task, the systems does not use local time. When the same task is displayed in the calendar it is the wrong time.
For example, if I was to set a time of 2pm local time (GMT+8), my calendar would show the task as starting at 10pm when it should show it starting at 2pm.

see pictures below:
![timezone](https://user-images.githubusercontent.com/66635367/164909470-a894d92b-5da6-41dd-84c4-b2a8988f2230.jpg)
![phpMyAdmin database Task table entry](https://user-images.githubusercontent.com/66635367/164909474-be3d817d-7b37-402f-ac96-ea223f5fd401.jpg)
![task pic 1](https://user-images.githubusercontent.com/66635367/164909478-7a31742e-f985-4293-a9ee-c0d6586b461a.jpg)
![task pic 2](https://user-images.githubusercontent.com/66635367/164909480-04ebe727-0c13-4023-8c95-37d440f00017.jpg)
![task pic 3](https://user-images.githubusercontent.com/66635367/164909485-a56f405c-0c99-49c0-903c-b996f1e91921.jpg)

**Comment by angeljgonzalezr** [comment]
Check your Universal Time on Ubuntu. 

![image](https://user-images.githubusercontent.com/44030546/175983428-02584e5c-7285-48b8-b64a-c717037889ef.png)

I has the same issue. Fix with: timedatectl set-timezone UTC

**Comment by scicali** [comment]
> I had the same issue. Fix with: timedatectl set-timezone UTC
This can be a good workaround!

**Comment by scicali** [comment]
@mcube27 Seems that all list views in NG Frontend have date in UTC.
Every user that is not in UTC show date in wrong timezone

**Comment by johnM2401** [comment]
Hey @rosshwalker 

This issue should be resolved as of the most recent release (v8.2.0)
https://docs.suitecrm.com/8.x/admin/releases/8.2/


Would you be able to give this a try in 8.2.0, and let us know how things go?

Thanks!
John

**Comment by binitasinghbrainvire** [comment]
Any update here? I am facing the same issue on custom module where I created a custom datetime field. My time zone is America/New york. On detailview datetime is 01/01/2024 12:00 PM, but on listview it shows 01/01/2024 11:00 AM. One hour difference on listview.

Please help

**Comment by scicali** [comment]
look #263
