### ISSUE TITLE
Incorrect version number in SuiteCRM 8.0.2

### ISSUE THREAD

**Issue by jameswill** [salesagility/SuiteCRM-Core#64]
Hi,

I have manually installed Suitecrm 8.0.2 and when I see Administrator --> About it shows 8.0.1 version.

On further debugging, I found that /public/legacy/suitecrm_version.php contains 8.0.1 which is incorrect.

Could you please replicate and resolve this ?

**Comment by clemente-raposo** [comment]
Hi @jameswill,

Many thanks for reporting this. We've just release 8.0.3 to address this issue.
Closing this issue.
