### ISSUE TITLE
Is there any plan to support "stock" module support？

### ISSUE THREAD

**Issue by pgy866** [salesagility/SuiteCRM-Core#65]
Is there any plan to support "stock" module support？

**Comment by pgorod** [comment]
I don't understand what you mean, can you please explain in more detail?

**Comment by pgy866** [comment]
> I don't understand what you mean, can you please explain in more detail?

product warehouse management,
Product Purchasing
warehouse location
Product inventory quantity
etc....
Product Supply, Marketing and Inventory Management System

desk
Service Type Goods
service hours
artificial
time consuming
rework
repair 
...etc

**Comment by pgorod** [comment]
No, there is no plan to support that. SuiteCRM is a CRM, not an inventory management app.

However, for simple cases, you can use Studio and Module Builder to customize SuiteCRM to do some of those things. 

(this discussion is more suitable to the Forums, here on Github it's more for reporting bugs to developers).
