### ISSUE TITLE
Install Support

### ISSUE THREAD

**Issue by pgy866** [salesagility/SuiteCRM-Core#66]
deepin linux 
The provided database host, username, and/or password is invalid, and a connection to the database could not be established. Please enter a valid host, username and password?

http://192.168.1.107/public/legacy/install.php
![截图_选择区域_20220131161545](https://user-images.githubusercontent.com/28694676/151759693-b991127d-2d11-43c8-80b1-54053b895f92.png)

![截图_选择区域_20220131161643](https://user-images.githubusercontent.com/28694676/151759811-6e56612a-3453-4ae6-97c3-6b27835618be.png)

**Comment by Mac-Rae** [comment]
Hi @pgy866,

This should be installed via the Suite8 installer found at the root. It appears to not have the correct redirects setup also.

Your installer when using S8 should appear like this;
![image](https://user-images.githubusercontent.com/45397629/151954876-4e32d788-47ee-4b89-9222-1d0a8cf1b48b.png)


Start to finish install instructions can be found here - https://docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing/

**Comment by pgy866** [comment]
@Mac-Rae Hello, my action has been installed, but it has some page faults?
![录屏_选择区域_20220203132427](https://user-images.githubusercontent.com/28694676/152286438-d255ca6d-4f52-459f-849d-135735db75a4.gif)
![录屏_选择区域_20220203132308](https://user-images.githubusercontent.com/28694676/152286459-e4eba549-43c2-4fc5-9128-b91972f0e0d2.gif)

**Comment by pgy866** [comment]
Here are my steps to install SuiteCRM 8 in deepin 20.4

```
sudo apt update && sudo apt install apache2

sudo apt install mariadb-server

sudo systemctl restart mysql

sudo mysql_secure_installation

sudo mysql -u root -p

create database yaoying;

CREATE USER 'yaoying'@'%' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON yaoying.* TO 'yaoying'@'%';

FLUSH PRIVILEGES;

EXIT;

sudo sed -i 's/bind-address = 127.0.0.1/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf

sudo service mysql restart

sudo apt-get install php libapache2-mod-php php-{cli,curl,common,intl,json,gd,mbstring,mysql,soap,xml,zip,imap,ldap,fpm}

sudo sed -i 's/memory_limit = 128M/memory_limit = 256M/' /etc/php/7.3/apache2/php.ini

sudo sed -i 's/post_max_size = 8M/post_max_size = 64M/' /etc/php/7.3/apache2/php.ini

sudo sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 64M/' /etc/php/7.3/apache2/php.ini

sudo sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php/7.3/apache2/php.ini

sudo sed -i 's/max_execution_time = 30/max_execution_time = 360/' /etc/php/7.3/apache2/php.ini

sudo sed -i 's/;date.timezone =/date.timezone = Asia/Shanghai/' /etc/php/7.3/apache2/php.ini

sudo deepin-editor /etc/apache2/sites-available/yaoying.conf

<VirtualHost *:80>
     ServerAdmin admin@yaoying.vip
     DocumentRoot /var/www/yaoying/public
     ServerName yaoying.vip
     ServerAlias www.yaoying.vip 192.168.1.109

     <Directory /var/www/yaoying/public>
          Options FollowSymlinks
          AllowOverride All
          Require all granted
     </Directory>

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined
    
     <Directory /var/www/yaoying/public>
            RewriteEngine on
            RewriteBase /
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*) index.php [PT,L]
    </Directory>
</VirtualHost>


sudo gedit /etc/hosts
127.0.0.1 yaoying.vip

sudo a2ensite yaoying.conf
sudo systemctl restart php7.3-fpm
sudo a2enmod rewrite
sudo systemctl restart apache2.service


sudo cd ./var/www/
sudo git clone git clone https://github.com/salesagility/SuiteCRM-Core.git yaoying
sudo cd ./var/www/yaoying
sudo find . -type d -not -perm 2755 -exec chmod 2755 {} \;
sudo find . -type f -not -perm 0644 -exec chmod 0644 {} \;
sudo find . ! -user www-data -exec chown www-data:www-data {} \;
sudo chmod +x bin/console


www.yaoying.vip
http://192.168.1.109/


```

**Comment by pgy866** [comment]
Thank you very much @tripitakabc
Through this modification, it is normal
The default is the link address filled in during the installation interface
`192.168.1.109legacy/`
Modify it to `192.168.1.109/legacy/`
Same error
Change it to` / legacy/`
Problem solving

https://github.com/salesagility/SuiteCRM-Core/issues/33
sudo deepin-editor /var/www/suitecrm8/public/legacy/.htaccess

![截图_选择区域_20220203151257](https://user-images.githubusercontent.com/28694676/152297627-becc8b72-476a-48ad-869e-d84451fd2648.png)

**Comment by web-sharp** [comment]
@pgy866 where did you set this base path?

I think I'm running into a similar issue on setup.  

Symfony\Component\DependencyInjection\Exception\RuntimeException:
Cannot autowire service "App\Install\Command\InstallExtensionAssets": argument "$name" of method "__construct()" is type-hinted "string", you should configure its value explicitly.

  at /var/www/html/suitecrm/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54
  at Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue()
     (/var/www/html/suitecrm/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81)
  at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue()
     (/var/www/html/suitecrm/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:32)
  at Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue()
     (/var/www/html/suitecrm/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46)
  at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process()
     (/var/www/html/suitecrm/vendor/symfony/dependency-injection/Compiler/Compiler.php:91)
  at Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
     (/var/www/html/suitecrm/vendor/symfony/dependency-injection/ContainerBuilder.php:731)
  at Symfony\Component\DependencyInjection\ContainerBuilder->compile()
     (/var/www/html/suitecrm/vendor/symfony/http-kernel/Kernel.php:541)
  at Symfony\Component\HttpKernel\Kernel->initializeContainer()
     (/var/www/html/suitecrm/core/backend/Kernel.php:124)
  at App\Kernel->getLegacyRoute()
     (/var/www/html/suitecrm/public/index.php:34)
