### ISSUE TITLE
Opportunity Amount Field - Error edit Opportunity Amount with comma configured as Decimal Symbol

### ISSUE THREAD

**Issue by mniubo** [salesagility/SuiteCRM-Core#73]
#### Issue

When you edit the opportunity Amount field when "," is configured as Decimal Symbol in Profile or System Options, you cannot use comma as a symbol in the field and if you uses dot instead doesn't record the data properly. In the result the decimals are considered as part of the main number.

This issue has been tested on SugarCRM versions 8.0.1 and 8.0.4.

Also has been tested in the Official Demo.

#### Expected Behavior

Use of comma as decimal symbol when you edit the field Opportunity Ammount.

#### Steps to Reproduce

1. Configure in Profile Advanced Options 1000s Separator:  "."
2. Configure in Profile Advanced Options 1000s Decimal Symbol::  ","
3. Edit the field Opportunity Ammount using decimals

#### Context

This bug avoids to use SugarCRM as a productive application due to this issue affect a basic CRM function.

#### Your Environment

* SuiteCRM Version used: 8.0.4 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Versión 99.0.4844.74 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4.28
* Operating System and version (e.g Ubuntu 16.04): Docker Buster

**Comment by scicali** [comment]
Alredy reported as #50 

Workaround:
in core/app/core/src/lib/services/formatters/number/number-formatter.service.ts at row 57 "insert return value;" to skip toInternalFormat function

then 

yarn run build:common && yarn run build:core && yarn run build:shell && ./bin/console cache:clear
