### ISSUE TITLE
System Name Not Updating Browser Tab Title

### ISSUE THREAD

**Issue by J-Wick4** [salesagility/SuiteCRM-Core#76]
**Admin -> System Settings -> System Name**

When updating the System Name, nothing happens, the browser tab still shows `SuiteCRM`

**Proper behavior**

When updating the System Name, the browser tab title should update and reflect the new name entered and saved, just as in v7.12.x. 

SuiteCRM v 8.1.0
PHP 7.4.28
MariaDB 10.4.24

**Comment by johnM2401** [comment]
Hey!

Just to let you know, I'm closing this issue as htis appears to have been resolved in SuiteCRM 8.2.0:
https://docs.suitecrm.com/8.x/admin/releases/8.2/

![image](https://user-images.githubusercontent.com/13675281/216604190-5752f0be-0a16-48c7-b48f-81bf4469d176.png)
![image](https://user-images.githubusercontent.com/13675281/216604214-8137d9d6-7cc3-4ee4-818c-5f44c12b81d4.png)

Please get in touch if you are still experiencing this, (or any other), issues with SuiteCRM!

Thanks!
