### ISSUE TITLE
NG Frontend: ListView items in Safari not appropriately rendered due to DatePipe conversion errors

### ISSUE THREAD

**Issue by bfoese** [salesagility/SuiteCRM-Core#81]
#### Issue

In Safari browser the DatePipe conversion fails and causes the view to not render appropriately. This can be reproduced in any SCRM ListView that displays the createdAt timestamp column.

#### Expected Behavior

DatePipe conversions being done with `date:getDateTimeFormat()` should work without throwing errors in Safari, to prevent render issues.

#### Actual Behavior

- In ListView components the content of the table rows is only rendered partially or not at all (blank table cells)
- browsers web development console shows occurrence of frontend errors from DatePipe conversions

#### Possible Fix

I am not proposing a fix for the root issue here. Only a fix to illustrate that the Safari render issues can be fixed by fixing the Date formatting issue.

When you change `{{field.value | date:getDateTimeFormat()}}` to `{{field.value}}` in file
`crm/core/app/core/src/lib/fields/datetime/templates/detail/datetime.component.html`
the ListView records are displayed correctly (but of course with unformatted dates)

#### Steps to Reproduce

1. Open https://suite8demo.suiteondemand.com/#/email-templates in Safari browser
2. Make sure the records creation date column is visible in the ListView

![image](https://user-images.githubusercontent.com/1623552/161952289-4152b8b7-747b-4ee9-8b73-031e490e1b66.png)

#### Context

Seems to only affect Safari browsers - we did not experienced date conversion issues in Chrome/Firefox. 
It probably affects all views where this date conversion is being used `date:getDateTimeFormat()`.

#### Your Environment

* SuiteCRM Version used: 8.0.4, 8.1.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 14.1.2 (16611.3.10.1.6)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): macOS 11.5.2

**Comment by johnM2401** [comment]
Hey Folks

This issue should (hopefully) be resolved as of SuiteCRM 8.2.0:
https://docs.suitecrm.com/8.x/admin/releases/8.2/
(Using the fix in the Merged MR 160)

Please let us know if you are still experiencing Date/Time errors with Safari, in recent versions of SuiteCRM
(or are experiencing any other issues with SuiteCRM)

Thanks!
