### ISSUE TITLE
Does enable_legacy_search works in 8.0?

### ISSUE THREAD

**Issue by Jonyx4** [salesagility/SuiteCRM-Core#85]
Tried to configure enable_legacy_search for Opportunities module, to have search and filter fixed on top of listview.

#### Issue
Tried configuring config_override.php with these parameters:

$sugar_config['enable_legacy_search'] = array('opportunities','accounts');
$sugar_config['enable_legacy_search'][] = 'opportunities';
$sugar_config['enable_legacy_search'][0] = 'opportunities';

But nothing happens, filter is not fixed on top

#### Expected Behavior
Tried to configure enable_legacy_search for Opportunities module, to have search and filter fixed on top of listview.

#### Actual Behavior
Nothing happens

Does enable_legacy_search works for version 8.0?

**Comment by johnM2401** [comment]
Hey there

I'm not sure what level of support this functionality has in Suite8, but it is indeed possible
Though we need to enable a few legacy features

So, initially, the Legacy Filter won't display at all on the new Suite8 views for modules that use this
(ie: Accounts and Opportunities)

So, we need to change both the Accounts and Opportunities Modules to use the Legacy Styling

This can be done as seen here:
https://community.suitecrm.com/t/compatibility-mode-in-suitecrm-8/83355


<br>

Then, you can add the following to your /public/legacy/config_override.php

```
$sugar_config['enable_legacy_search'] = array('Opportunities','Accounts');

```
(With the module-names capitalised)


<br>

Then, after clearing both Browser & CRM Cache, as well as running a Quick Repair and Rebuild

You *should* see something like this:
![image](https://user-images.githubusercontent.com/13675281/163830037-8d12c17b-376f-48f2-9cd9-638d75490cbf.png)
