### ISSUE TITLE
Some filter date range options doesn't work

### ISSUE THREAD

**Issue by scicali** [salesagility/SuiteCRM-Core#86]
Date range types

last_7_days 
next_7_days 
last_30_days 
next_30_days 
last_month 
next_month 
last_year 
this_year 
next_year

doesn't work

#### Issue
If u try to filter a date field with range search enable, using those types in ListView nothing happen

#### Expected Behavior
Filter must work

#### Actual Behavior
Nothing happen

#### Possible Fix
In public\legacy\include\portability\FilterMapper\filter_operator_map.php

last_7_days 
next_7_days 
last_30_days 
next_30_days 
last_month 
next_month 
last_year 
this_year 
next_year

types hasn't item `'range_{field}_{type}' => '[{operator}]'` set

Behavior can be override in `custom/application/Ext/FilterOperatorMap/filter_operator_map.ext.php`,
but I Think it's a bug

#### Steps to Reproduce
1. Enable date type to range search
2. Filter date field with those range types

#### Your Environment

* SuiteCRM Version used: 8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 99.0.1
* Environment name and version (e.g. MySQL, PHP 7): php 7.4
* Operating System and version (e.g Ubuntu 16.04): DEbian 11

**Comment by lukio** [comment]
Hi  @clemente-raposo I'm working on 8.3.0 suitecrm version that has https://github.com/salesagility/SuiteCRM-Core/pull/89 included, but the filter date range it's not working  :/
