### ISSUE TITLE
Serve Angular app locally

### ISSUE THREAD

**Issue by bfoese** [salesagility/SuiteCRM-Core#9]
#### Issue
Not able to serve the frontend shell app locally by the command provided in package.json: 
"start:shell": "ng serve shell  -o --port 5000"

#### Expected Behavior
Shell application should be served under http://localhost:5000

#### Actual Behavior
App won't be served, instead error message on terminal: 
```
$ng serve shell  -o --port 5000
✔ Browser application bundle generation complete.
(node:36445) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:36445) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
```
#### Possible Fix
I couldn't trace down the error, but since this is webpack related, I would like to suggest to consider an upgrade to Angular 12 before the release candidate of Suite CRM 8. Angular 12 already uses Webpack 5 out of the box and you would not need to override the Webpack version in package.json anymore. 

#### Steps to Reproduce
1. Checkout source code
2. Optional: delete 'yarn.lock' file
3. Install dependencies: ```yarn install```
4. Copy ```proxy.conf.env.json``` and rename the copy to ```proxy.conf.local.json```
5. Run  ```yarn run start:shell```

#### Context
Theme development would be much easier, if the frontend could be served locally with automatic application reload on file changes instead of needing to rebuild it

#### Your Environment
* SuiteCRM Version used: 8.0.0-beta.2
* Operating System and version (e.g Ubuntu 16.04): MacOS Big Sur

**Comment by bfoese** [comment]
The error is not present anymore after updating to `8.0.0-beta.3`. Thanks for upgrading to Angular 12!

**Comment by clemente-raposo** [comment]
Hi @bfoese, no problem! Thanks for the feedback an for trying out SuiteCRM 8 Beta. If you have more feedback, please let us know.
