### ISSUE TITLE
Suitecrm 8.1.1 installation issue

### ISSUE THREAD

**Issue by sugen** [salesagility/SuiteCRM-Core#99]
![suitecrm](https://user-images.githubusercontent.com/1313059/170425115-cee4c5b8-0c00-4baf-808b-55cf335004be.png)

**Comment by sebastianbrosch** [comment]
You can install SuiteCRM 8.1.1 on a different URL. You are using `http://yourserver.com/Suite-CRM-Directory/install.php` but you can also use `http://yourserver.com/Suite-CRM-Directory/legacy/install.php` instead.

![image](https://user-images.githubusercontent.com/6590066/170475552-1c89a718-ace1-46c7-9103-4de1a4cae274.png)
